const PRODUCTS={plain:{ru:'Обычный хлеб',en:'Plain bread',es:'Pan clásico'},pumpkin:{ru:'Хлеб из тыквы',en:'Pumpkin bread',es:'Pan de calabaza'}};
const TEXT={
ru:{bakery:'Пекарня',plan:'План выпечки',recipes:'Рецептуры',purchase:'Закупка',stock:'Склад хлеба',planTitle:'План выпечки и доставки',planText:'Добавляйте даты и планируйте каждый хлеб в штуках.',addBake:'+ Добавить выпечку',today:'Сегодня',planned:'Запланировано',ordered:'Заказано',reserve:'Свободно',recipeTitle:'Рецептуры на 1 хлеб 600 г',recipeText:'Стартовая закладка. После пробной выпечки скорректируйте её по фактическому весу остывшего хлеба.',purchaseTitle:'Список закупки',purchaseText:'Расчёт по плану выпечки с учётом остатков и страхового запаса.',print:'Печать',ingredient:'Ингредиент',required:'Нужно',ingredientStock:'Остаток',margin:'Запас',buy:'Купить',stockTitle:'Склад готового хлеба',stockText:'Остатки и движения учитываются в штуках.',movement:'+ Движение',date:'Дата',product:'Хлеб',operation:'Операция',quantity:'Количество',note:'Примечание',newBake:'Новая выпечка',bakeDate:'Дата выпечки',deliveryDate:'Дата доставки',plannedPiecesLabel:'План, шт.',cutoff:'Приём заказов до',accepting:'Принимать заказы',cancel:'Отмена',save:'Сохранить',newMovement:'Движение хлеба',open:'Заказы открыты',closed:'Закрыто',delivery:'Доставка',cutoffShort:'Заказ до',empty:'На этой неделе выпечек нет',pcs:'шт.',orderedShort:'заказано'},
en:{bakery:'Bakery',plan:'Bake plan',recipes:'Recipes',purchase:'Purchasing',stock:'Bread stock',planTitle:'Bake and delivery plan',planText:'Add dates and plan each bread in pieces.',addBake:'+ Add bake',today:'Today',planned:'Planned',ordered:'Ordered',reserve:'Available',recipeTitle:'Recipes per piece',recipeText:'Enter the actual ingredient use for one loaf.',purchaseTitle:'Purchase list',purchaseText:'Calculated from the bake plan, stock and safety margin.',print:'Print',ingredient:'Ingredient',required:'Required',ingredientStock:'Stock',margin:'Margin',buy:'Buy',stockTitle:'Finished bread stock',stockText:'Stock and movements are counted in pieces.',movement:'+ Movement',date:'Date',product:'Bread',operation:'Operation',quantity:'Quantity',note:'Note',newBake:'New bake',bakeDate:'Bake date',deliveryDate:'Delivery date',plannedPiecesLabel:'Plan, pcs',cutoff:'Order cutoff',accepting:'Accept orders',cancel:'Cancel',save:'Save',newMovement:'Bread movement',open:'Orders open',closed:'Closed',delivery:'Delivery',cutoffShort:'Cutoff',empty:'No bakes this week',pcs:'pcs',orderedShort:'ordered'},
es:{bakery:'Panadería',plan:'Plan de horneado',recipes:'Recetas',purchase:'Compras',stock:'Stock de pan',planTitle:'Plan de horneado y entrega',planText:'Añade fechas y planifica cada pan por unidades.',addBake:'+ Añadir horneado',today:'Hoy',planned:'Planificado',ordered:'Pedido',reserve:'Disponible',recipeTitle:'Recetas por unidad',recipeText:'Introduce el consumo real para un pan.',purchaseTitle:'Lista de compras',purchaseText:'Cálculo según el plan, existencias y margen de seguridad.',print:'Imprimir',ingredient:'Ingrediente',required:'Necesario',ingredientStock:'Existencias',margin:'Margen',buy:'Comprar',stockTitle:'Stock de pan terminado',stockText:'Las existencias y movimientos se cuentan por unidades.',movement:'+ Movimiento',date:'Fecha',product:'Pan',operation:'Operación',quantity:'Cantidad',note:'Nota',newBake:'Nuevo horneado',bakeDate:'Fecha de horneado',deliveryDate:'Fecha de entrega',plannedPiecesLabel:'Plan, uds.',cutoff:'Cierre de pedidos',accepting:'Aceptar pedidos',cancel:'Cancelar',save:'Guardar',newMovement:'Movimiento de pan',open:'Pedidos abiertos',closed:'Cerrado',delivery:'Entrega',cutoffShort:'Cierre',empty:'No hay horneados esta semana',pcs:'uds.',orderedShort:'pedido'}
};
const DEFAULT_RECIPES={
 plain:[{name:'Мука пшеничная',qty:400,unit:'g',stock:0,margin:5},{name:'Кефир / пахта',qty:300,unit:'ml',stock:0,margin:5},{name:'Соль',qty:7,unit:'g',stock:0,margin:5},{name:'Сода пищевая',qty:5,unit:'g',stock:0,margin:5},{name:'Масло растительное',qty:12,unit:'ml',stock:0,margin:5}],
 pumpkin:[{name:'Мука пшеничная',qty:350,unit:'g',stock:0,margin:5},{name:'Пюре тыквенное',qty:160,unit:'g',stock:0,margin:10},{name:'Кефир / пахта',qty:190,unit:'ml',stock:0,margin:5},{name:'Соль',qty:7,unit:'g',stock:0,margin:5},{name:'Сода пищевая',qty:5,unit:'g',stock:0,margin:5},{name:'Масло растительное',qty:15,unit:'ml',stock:0,margin:5}]
};
let lang=localStorage.getItem('panora-admin-lang')||'ru';
let weekStart=startOfWeek(new Date());
let plans=read('panora-production-plans',[]);
let recipes=read('panora-recipes',DEFAULT_RECIPES);
let purchaseDateFilter='all';
if(localStorage.getItem('panora-recipes-version')!=='2'){
 recipes=structuredClone(DEFAULT_RECIPES);
 localStorage.setItem('panora-recipes',JSON.stringify(recipes));
 localStorage.setItem('panora-recipes-version','2');
}
let movements=read('panora-stock-movements',[]);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], t=k=>TEXT[lang][k]||k;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||structuredClone(fallback)}catch{return structuredClone(fallback)}}
function store(key,value){localStorage.setItem(key,JSON.stringify(value));$('#saveState').textContent=lang==='ru'?'Сохранено':lang==='es'?'Guardado':'Saved'}
function startOfWeek(date){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}
function iso(d){return d.toISOString().slice(0,10)}
function fmt(d,opts={day:'numeric',month:'short'}){return new Intl.DateTimeFormat(lang==='ru'?'ru-RU':lang==='es'?'es-ES':'en-GB',opts).format(new Date(d+'T12:00:00'))}
function productName(id){return PRODUCTS[id]?.[lang]||id}
function applyLanguage(){$('#adminLanguage').value=lang;$$('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));renderAll()}
function renderAll(){renderPlan();renderRecipes();renderPurchase();renderStock()}
function renderPlan(){const end=new Date(weekStart);end.setDate(end.getDate()+6);$('#periodLabel').textContent=`${fmt(iso(weekStart))} — ${fmt(iso(end),{day:'numeric',month:'short',year:'numeric'})}`;const visible=plans.filter(p=>p.bakeDate>=iso(weekStart)&&p.bakeDate<=iso(end)).sort((a,b)=>a.bakeDate.localeCompare(b.bakeDate));const planned=visible.reduce((s,p)=>s+Number(p.planned),0),ordered=visible.reduce((s,p)=>s+Number(p.ordered||0),0);$('#plannedPieces').textContent=`${planned} ${t('pcs')}`;$('#orderedPieces').textContent=`${ordered} ${t('pcs')}`;$('#freePieces').textContent=`${Math.max(0,planned-ordered)} ${t('pcs')}`;$('#planList').innerHTML=visible.length?visible.map(p=>{const percent=p.planned?Math.min(100,Math.round((p.ordered||0)/p.planned*100)):0;return `<article class="plan-card"><div class="date"><strong>${fmt(p.bakeDate,{weekday:'short',day:'numeric',month:'short'})}</strong><small>${t('delivery')}: ${fmt(p.deliveryDate)}</small></div><div class="product"><strong>${productName(p.product)}</strong><small>${t('cutoffShort')}: ${new Date(p.cutoff).toLocaleString()}</small></div><div><strong>${p.planned} ${t('pcs')}</strong><small>${p.ordered||0} ${t('orderedShort')}</small><div class="progress"><i style="width:${percent}%"></i></div></div><div><input class="ordered-input" data-order="${p.id}" type="number" min="0" value="${p.ordered||0}" aria-label="${t('ordered')}"></div><span class="status ${p.open?'':'closed'}">${p.open?t('open'):t('closed')}</span><button class="icon-delete" data-delete-plan="${p.id}">×</button></article>`}).join(''):`<article class="plan-card"><div>${t('empty')}</div></article>`;$$('[data-delete-plan]').forEach(b=>b.onclick=()=>{plans=plans.filter(p=>p.id!==b.dataset.deletePlan);store('panora-production-plans',plans);renderAll()});$$('[data-order]').forEach(i=>i.onchange=()=>{const p=plans.find(x=>x.id===i.dataset.order);p.ordered=Math.max(0,Number(i.value));store('panora-production-plans',plans);renderAll()})}
function renderRecipes(){$('#recipeList').innerHTML=Object.keys(PRODUCTS).map(pid=>`<article class="recipe-card"><h3>${productName(pid)}</h3><div>${recipes[pid].map((r,i)=>`<div class="recipe-row"><input data-recipe-name="${pid}:${i}" value="${r.name}"><input data-recipe-qty="${pid}:${i}" type="number" min="0" step="0.01" value="${r.qty}"><select data-recipe-unit="${pid}:${i}"><option ${r.unit==='g'?'selected':''}>g</option><option ${r.unit==='ml'?'selected':''}>ml</option><option ${r.unit==='pcs'?'selected':''}>pcs</option></select><button class="recipe-delete" data-delete-ingredient="${pid}:${i}" type="button">×</button></div>`).join('')}</div><button class="secondary" data-add-ingredient="${pid}">+ ${t('ingredient')}</button></article>`).join('');$$('[data-recipe-name],[data-recipe-qty],[data-recipe-unit]').forEach(e=>e.onchange=()=>{const [pid,i]=(e.dataset.recipeName||e.dataset.recipeQty||e.dataset.recipeUnit).split(':');if(e.dataset.recipeName)recipes[pid][i].name=e.value;if(e.dataset.recipeQty)recipes[pid][i].qty=Number(e.value);if(e.dataset.recipeUnit)recipes[pid][i].unit=e.value;store('panora-recipes',recipes);renderPurchase()});$$('[data-add-ingredient]').forEach(b=>b.onclick=()=>{recipes[b.dataset.addIngredient].push({name:t('ingredient'),qty:0,unit:'g',stock:0,margin:5});store('panora-recipes',recipes);renderAll()});$$('[data-delete-ingredient]').forEach(b=>b.onclick=()=>{const [pid,index]=b.dataset.deleteIngredient.split(':'),item=recipes[pid][Number(index)],question=lang==='ru'?`Удалить ингредиент «${item.name||'без названия'}»?`:lang==='es'?`¿Eliminar «${item.name||'sin nombre'}»?`:`Delete “${item.name||'unnamed'}”?`;if(!confirm(question))return;recipes[pid].splice(Number(index),1);store('panora-recipes',recipes);renderAll()})}
function purchaseDates(){return [...new Set(plans.filter(p=>p.bakeDate>=iso(new Date())).map(p=>p.bakeDate))].sort()}
function renderPurchaseFilter(){const select=$('#purchaseDateFilter');if(!select)return;const dates=purchaseDates();if(purchaseDateFilter!=='all'&&!dates.includes(purchaseDateFilter))purchaseDateFilter='all';const allLabel=lang==='ru'?'Все даты вместе':lang==='es'?'Todas las fechas juntas':'All dates together';select.innerHTML=`<option value="all">${allLabel}</option>`+dates.map((date,index)=>`<option value="${date}">${index===0?(lang==='ru'?'Первая выпечка':lang==='es'?'Primer horneado':'First bake'):index===1?(lang==='ru'?'Вторая выпечка':lang==='es'?'Segundo horneado':'Second bake'):(lang==='ru'?`Выпечка ${index+1}`:lang==='es'?`Horneado ${index+1}`:`Bake ${index+1}`)} — ${fmt(date,{weekday:'short',day:'numeric',month:'short'})}</option>`).join('');select.value=purchaseDateFilter;select.onchange=()=>{purchaseDateFilter=select.value;renderPurchase()};$('#purchaseFilterSummary').textContent=purchaseDateFilter==='all'?`${dates.length} ${lang==='ru'?'дат':lang==='es'?'fechas':'dates'}`:fmt(purchaseDateFilter,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function ingredientTotals(){const totals={};plans.filter(p=>p.bakeDate>=iso(new Date())&&(purchaseDateFilter==='all'||p.bakeDate===purchaseDateFilter)).forEach(p=>(recipes[p.product]||[]).forEach(r=>{const key=`${r.name}|${r.unit}`;totals[key]??={name:r.name,unit:r.unit,required:0,stock:Number(r.stock||0),margin:Number(r.margin||5)};totals[key].required+=Number(p.planned)*Number(r.qty)}));return Object.values(totals)}
function niceQty(n,unit){if(unit==='g'&&n>=1000)return `${(n/1000).toFixed(2)} kg`;if(unit==='ml'&&n>=1000)return `${(n/1000).toFixed(2)} l`;return `${Math.ceil(n*100)/100} ${unit}`}
function renderPurchase(){renderPurchaseFilter();const rows=ingredientTotals();$('#purchaseRows').innerHTML=rows.length?rows.map((r,i)=>{const buy=Math.max(0,r.required*(1+r.margin/100)-r.stock);return `<tr><td><strong>${r.name}</strong></td><td>${niceQty(r.required,r.unit)}</td><td><input data-stock="${i}" type="number" min="0" value="${r.stock}"> ${r.unit}</td><td><input data-margin="${i}" type="number" min="0" value="${r.margin}">%</td><td><strong>${niceQty(buy,r.unit)}</strong></td></tr>`}).join(''):`<tr><td colspan="5">${t('empty')}</td></tr>`;$$('[data-stock],[data-margin]').forEach(e=>e.onchange=()=>{const row=rows[Number(e.dataset.stock??e.dataset.margin)];Object.values(recipes).flat().filter(r=>r.name===row.name&&r.unit===row.unit).forEach(r=>{if(e.dataset.stock!==undefined)r.stock=Number(e.value);else r.margin=Number(e.value)});store('panora-recipes',recipes);renderPurchase()})}
function signed(m){return ['shipped','written_off'].includes(m.type)?-Number(m.quantity):Number(m.quantity)}
function renderStock(){const balances=Object.keys(PRODUCTS).map(pid=>({pid,qty:movements.filter(m=>m.product===pid).reduce((s,m)=>s+signed(m),0)}));$('#stockCards').innerHTML=balances.map(x=>`<article><span>${productName(x.pid)}</span><strong>${x.qty} ${t('pcs')}</strong></article>`).join('');$('#movementRows').innerHTML=movements.slice().reverse().map(m=>`<tr><td>${fmt(m.date)}</td><td>${productName(m.product)}</td><td>${m.type}</td><td>${signed(m)>0?'+':''}${signed(m)} ${t('pcs')}</td><td>${m.note||''}</td></tr>`).join('')}
$$('.admin-nav button').forEach(b=>b.onclick=()=>{$$('.admin-nav button,.view').forEach(e=>e.classList.remove('active'));b.classList.add('active');$('#view-'+b.dataset.view).classList.add('active')});
$('#adminLanguage').onchange=e=>{lang=e.target.value;localStorage.setItem('panora-admin-lang',lang);applyLanguage()};
$('#prevWeek').onclick=()=>{weekStart.setDate(weekStart.getDate()-7);renderPlan()};$('#nextWeek').onclick=()=>{weekStart.setDate(weekStart.getDate()+7);renderPlan()};$('#today').onclick=()=>{weekStart=startOfWeek(new Date());renderPlan()};
const planDateJump=$('#planDateJump');
if(planDateJump){
  planDateJump.value=iso(new Date());
  $('#goToPlanDate').onclick=()=>{if(!planDateJump.value)return;weekStart=startOfWeek(new Date(`${planDateJump.value}T12:00:00`));renderPlan()};
  const label=$('#planDateJumpLabel');
  if(label)label.textContent=lang==='ru'?'Выбрать дату':lang==='es'?'Elegir fecha':'Choose date';
  $('#goToPlanDate').textContent=lang==='ru'?'Показать неделю':lang==='es'?'Mostrar semana':'Show week';
  $('#prevWeek').textContent=lang==='ru'?'← Предыдущая неделя':lang==='es'?'← Semana anterior':'← Previous week';
  $('#nextWeek').textContent=lang==='ru'?'Следующая неделя →':lang==='es'?'Semana siguiente →':'Next week →';
  $('#today').textContent=lang==='ru'?'Текущая неделя':lang==='es'?'Semana actual':'Current week';
}
$('#addPlan').onclick=()=>{const f=$('#planForm'),b=new Date();b.setDate(b.getDate()+3);f.bakeDate.value=iso(b);f.deliveryDate.value=iso(b);const c=new Date(b);c.setDate(c.getDate()-2);c.setHours(18,0,0,0);f.cutoff.value=c.toISOString().slice(0,16);$('#planDialog').showModal()};
$('#savePlan').onclick=e=>{e.preventDefault();const f=new FormData($('#planForm'));plans.push({id:crypto.randomUUID(),bakeDate:f.get('bakeDate'),deliveryDate:f.get('deliveryDate'),product:f.get('product'),planned:Number(f.get('planned')),ordered:0,cutoff:f.get('cutoff'),open:f.get('open')==='on'});store('panora-production-plans',plans);$('#planDialog').close();renderAll()};
$('#addMovement').onclick=()=>$('#movementDialog').showModal();$('#saveMovement').onclick=e=>{e.preventDefault();const f=new FormData($('#movementForm'));movements.push({id:crypto.randomUUID(),date:iso(new Date()),product:f.get('product'),type:f.get('type'),quantity:Number(f.get('quantity')),note:f.get('note')});store('panora-stock-movements',movements);$('#movementDialog').close();$('#movementForm').reset();renderStock()};
$('#printPurchase').onclick=()=>window.print();applyLanguage();
