const cRead=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
let restaurants=cRead('panora-restaurants',[]),orders=cRead('panora-orders',[]),payments=cRead('panora-payments',[]),deliveryNotes=cRead('panora-delivery-notes',[]);
const cSave=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const restaurant=id=>restaurants.find(r=>r.id===id);
const orderTotal=o=>o.items.reduce((sum,i)=>sum+i.quantity*restaurant(o.restaurantId).prices[i.product],0);
const shippedFor=id=>deliveryNotes.filter(n=>n.restaurantId===id).reduce((s,n)=>s+n.total,0);
const paidFor=id=>payments.filter(p=>p.restaurantId===id).reduce((s,p)=>s+p.amount,0);
function fillRestaurants(){const options=restaurants.map(r=>`<option value="${r.id}">${r.name}</option>`).join('');document.querySelector('#orderRestaurant').innerHTML=options;document.querySelector('#paymentRestaurant').innerHTML=options}
function renderRestaurants(){const root=document.querySelector('#restaurantCards');root.innerHTML=restaurants.length?restaurants.map(r=>`<article class="restaurant-card"><span class="tag">Личный кабинет</span><h3>${r.name}</h3><p>${r.email}<br>${r.address||''}</p><label class="price-row"><span>Обычный хлеб</span><span><input data-price="${r.id}:plain" type="number" min="0" step="0.01" value="${r.prices.plain.toFixed(2)}"> €</span></label><label class="price-row"><span>Хлеб из тыквы</span><span><input data-price="${r.id}:pumpkin" type="number" min="0" step="0.01" value="${r.prices.pumpkin.toFixed(2)}"> €</span></label><div class="debt-row"><span>Задолженность</span><strong>${euro(shippedFor(r.id)-paidFor(r.id))}</strong></div></article>`).join(''):'<div class="empty-row">Добавьте первый ресторан и назначьте ему индивидуальные цены.</div>';document.querySelectorAll('[data-price]').forEach(i=>i.onchange=()=>{const [id,pid]=i.dataset.price.split(':');restaurant(id).prices[pid]=Number(i.value);cSave('panora-restaurants',restaurants);renderCommerce()});fillRestaurants()}
function renderOrders(){const body=document.querySelector('#orderRows');body.innerHTML=orders.length?orders.slice().reverse().map(o=>`<tr><td>PN-${String(o.number).padStart(4,'0')}</td><td>${o.date}</td><td>${restaurant(o.restaurantId)?.name||'—'}</td><td>${o.items.map(i=>`${i.product==='plain'?'Обычный':'Тыквенный'} — ${i.quantity} шт.`).join('<br>')}</td><td>${euro(orderTotal(o))}</td><td><span class="tag">${o.status==='shipped'?'Отгружен':'Подтверждён'}</span></td><td>${o.status==='shipped'?`<button class="action-small" data-note="${o.id}">Накладная</button>`:`<button class="action-small ship" data-ship="${o.id}">Отгрузить</button>`}</td></tr>`).join(''):'<tr><td class="empty-row" colspan="7">Заказов пока нет.</td></tr>';document.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>openShipment(b.dataset.ship));document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>printNote(b.dataset.note))}
function renderAccounting(){let shipped=0,paid=0;document.querySelector('#accountRows').innerHTML=restaurants.length?restaurants.map(r=>{const s=shippedFor(r.id),p=paidFor(r.id),last=[...deliveryNotes.filter(n=>n.restaurantId===r.id).map(n=>n.date),...payments.filter(x=>x.restaurantId===r.id).map(x=>x.date)].sort().pop()||'—';shipped+=s;paid+=p;return `<tr><td><strong>${r.name}</strong></td><td>${euro(s)}</td><td>${euro(p)}</td><td class="${s-p>0?'negative':''}"><strong>${euro(s-p)}</strong></td><td>${last}</td></tr>`}).join(''):'<tr><td class="empty-row" colspan="5">Ресторанов пока нет.</td></tr>';document.querySelector('#totalShipped').textContent=euro(shipped);document.querySelector('#totalPaid').textContent=euro(paid);document.querySelector('#totalDebt').textContent=euro(shipped-paid)}
function renderCommerce(){renderRestaurants();renderOrders();renderAccounting()}
document.querySelector('#addRestaurant').onclick=()=>document.querySelector('#restaurantDialog').showModal();
document.querySelector('#saveRestaurant').onclick=e=>{e.preventDefault();const f=new FormData(document.querySelector('#restaurantForm'));restaurants.push({id:crypto.randomUUID(),name:f.get('name'),email:f.get('email'),phone:f.get('phone'),address:f.get('address'),prices:{plain:Number(f.get('plainPrice')),pumpkin:Number(f.get('pumpkinPrice'))}});cSave('panora-restaurants',restaurants);document.querySelector('#restaurantDialog').close();document.querySelector('#restaurantForm').reset();renderCommerce()};
document.querySelector('#addOrder').onclick=()=>{if(!restaurants.length){alert('Сначала добавьте ресторан.');return}const f=document.querySelector('#orderForm');const d=new Date();d.setDate(d.getDate()+3);f.date.value=d.toISOString().slice(0,10);document.querySelector('#orderDialog').showModal()};
document.querySelector('#saveOrder').onclick=e=>{e.preventDefault();const f=new FormData(document.querySelector('#orderForm')),plain=Number(f.get('plain')),pumpkin=Number(f.get('pumpkin'));if(plain+pumpkin<12){alert('Минимальный заказ — 12 шт.');return}const items=[];if(plain)items.push({product:'plain',quantity:plain});if(pumpkin)items.push({product:'pumpkin',quantity:pumpkin});orders.push({id:crypto.randomUUID(),number:(orders.at(-1)?.number||0)+1,restaurantId:f.get('restaurant'),date:f.get('date'),items,status:'confirmed'});cSave('panora-orders',orders);document.querySelector('#orderDialog').close();document.querySelector('#orderForm').reset();renderCommerce()};
function openShipment(id){const o=orders.find(x=>x.id===id),total=orderTotal(o);document.querySelector('#shipmentForm').orderId.value=id;document.querySelector('#shipmentSummary').innerHTML=`<strong>PN-${String(o.number).padStart(4,'0')} · ${restaurant(o.restaurantId).name}</strong><br>${o.items.map(i=>`${i.product==='plain'?'Обычный хлеб':'Хлеб из тыквы'}: ${i.quantity} шт.`).join('<br>')}<hr>К отгрузке: <strong>${euro(total)}</strong>`;document.querySelector('#shipmentDialog').showModal()}
document.querySelector('#confirmShipment').onclick=e=>{e.preventDefault();const f=new FormData(document.querySelector('#shipmentForm')),o=orders.find(x=>x.id===f.get('orderId')),total=orderTotal(o),paid=Math.min(total,Math.max(0,Number(f.get('paid'))));o.status='shipped';const note={id:crypto.randomUUID(),number:deliveryNotes.length+1,orderId:o.id,restaurantId:o.restaurantId,date:new Date().toISOString().slice(0,10),items:structuredClone(o.items),prices:structuredClone(restaurant(o.restaurantId).prices),total,paid,balanceAfter:shippedFor(o.restaurantId)+total-paidFor(o.restaurantId)-paid};deliveryNotes.push(note);if(paid)payments.push({id:crypto.randomUUID(),restaurantId:o.restaurantId,date:note.date,amount:paid,method:f.get('method'),note:`Оплата по накладной DN-${note.number}`});o.items.forEach(i=>movements.push({id:crypto.randomUUID(),date:note.date,product:i.product,type:'shipped',quantity:i.quantity,note:`Накладная DN-${note.number}`}));cSave('panora-orders',orders);cSave('panora-delivery-notes',deliveryNotes);cSave('panora-payments',payments);store('panora-stock-movements',movements);document.querySelector('#shipmentDialog').close();renderCommerce();renderStock();printNote(o.id)};
document.querySelector('#addPayment').onclick=()=>{if(!restaurants.length){alert('Сначала добавьте ресторан.');return}document.querySelector('#paymentDialog').showModal()};
document.querySelector('#savePayment').onclick=e=>{e.preventDefault();const f=new FormData(document.querySelector('#paymentForm'));payments.push({id:crypto.randomUUID(),restaurantId:f.get('restaurant'),date:new Date().toISOString().slice(0,10),amount:Number(f.get('amount')),method:f.get('method'),note:f.get('note')});cSave('panora-payments',payments);document.querySelector('#paymentDialog').close();document.querySelector('#paymentForm').reset();renderCommerce()};
function printNote(orderId){const n=deliveryNotes.find(x=>x.orderId===orderId),r=restaurant(n.restaurantId),w=window.open('','_blank');w.document.write(`<title>Накладная DN-${n.number}</title><style>body{font:15px Arial;max-width:800px;margin:40px auto}h1{font:36px Georgia}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ccc;text-align:left}.total{text-align:right;font-size:20px}.sign{margin-top:70px;display:flex;justify-content:space-between}</style><h1>Panora</h1><h2>Накладная DN-${String(n.number).padStart(4,'0')}</h2><p>Дата: ${n.date}<br>Ресторан: <strong>${r.name}</strong><br>Адрес: ${r.address||'—'}</p><table><tr><th>Товар</th><th>Количество</th><th>Цена</th><th>Сумма</th></tr>${n.items.map(i=>`<tr><td>${i.product==='plain'?'Обычный хлеб':'Хлеб из тыквы'}</td><td>${i.quantity} шт.</td><td>${euro(n.prices[i.product])}</td><td>${euro(i.quantity*n.prices[i.product])}</td></tr>`).join('')}</table><p class="total">Итого: <strong>${euro(n.total)}</strong><br>Оплачено: ${euro(n.paid)}<br>Задолженность после операции: ${euro(n.balanceAfter)}</p><div class="sign"><span>Panora __________________</span><span>Ресторан __________________</span></div>`);w.document.close();w.print()}
renderCommerce();
