(function(){
  const root=document.querySelector('#deliveryCard'),cfg=window.PANORA_SUPABASE||{},sessionKey='panora-restaurant-cloud-session',queueKey='panora-delivery-confirmation-queue';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const token=new URLSearchParams(location.search).get('t')||'',valid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(token);
  let session=JSON.parse(localStorage.getItem(sessionKey)||'null');
  const show=(title,text,action='')=>root.innerHTML=`<div class="error"><strong>${esc(title)}</strong><br>${esc(text)}</div>${action}`;
  async function refresh(){if(!session?.refresh_token)return false;const r=await fetch(`${cfg.url}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});if(!r.ok)return false;session=await r.json();localStorage.setItem(sessionKey,JSON.stringify(session));return true}
  async function rpc(name,body,retry=true){const r=await fetch(`${cfg.url}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:cfg.publishableKey,Authorization:`Bearer ${session?.access_token||''}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.status===401&&retry&&await refresh())return rpc(name,body,false);if(!r.ok)throw new Error(String(r.status));return r.json()}
  const queued=()=>JSON.parse(localStorage.getItem(queueKey)||'[]');
  function savePending(receiver){const q=queued().filter(x=>x.token!==token);q.push({token,receiver,createdAt:new Date().toISOString()});localStorage.setItem(queueKey,JSON.stringify(q))}
  async function flush(){if(!navigator.onLine||!session?.access_token)return;const left=[];for(const item of queued()){try{const rows=await rpc('panora_confirm_delivery',{p_token:item.token,p_receiver:item.receiver});if(!rows?.length)throw new Error()}catch{left.push(item)}}localStorage.setItem(queueKey,JSON.stringify(left))}
  function render(d){const items=Array.isArray(d.items)?d.items:[];root.innerHTML=`${d.customer_confirmed_at?`<div class="success"><strong>Поставка подтверждена</strong><br>${new Date(d.customer_confirmed_at).toLocaleString('ru-RU')}</div>`:''}<h2>Поставка DN-${String(d.note_number).padStart(4,'0')}</h2><div class="meta"><div><small>Заказ</small><strong>PN-${String(d.order_number).padStart(4,'0')}</strong></div><div><small>Дата поставки</small><strong>${esc(d.delivery_date||String(d.delivered_at).slice(0,10))}</strong></div></div><table class="items"><thead><tr><th>Товар</th><th>Количество</th></tr></thead><tbody>${items.map(i=>`<tr><td>${esc(i.name_ru||i.product_id)}</td><td>${i.quantity} шт.</td></tr>`).join('')}</tbody></table>${d.customer_confirmed_at?'':`<form id="confirmForm" class="confirm-form"><label><span>Имя получателя</span><input name="receiver" minlength="2" maxlength="120" autocomplete="name" required></label><label class="check"><input name="accepted" type="checkbox" required><span>Количество и состояние товара проверены. Подтверждаю получение.</span></label><button>Подтвердить получение</button></form>`}`;
    document.querySelector('#confirmForm')?.addEventListener('submit',async e=>{e.preventDefault();const receiver=String(new FormData(e.currentTarget).get('receiver')).trim(),button=e.currentTarget.querySelector('button');button.disabled=true;try{if(!navigator.onLine){savePending(receiver);root.insertAdjacentHTML('afterbegin','<div class="pending"><strong>Ожидает отправки</strong><br>Подтверждение сохранено и будет проверено после появления интернета.</div>');e.currentTarget.remove();return}const rows=await rpc('panora_confirm_delivery',{p_token:token,p_receiver:receiver});if(!rows?.length)throw new Error();await load()}catch{show('Не удалось подтвердить','Код недействителен, истёк или принадлежит другому ресторану.')}finally{button.disabled=false}})}
  async function load(){if(!valid)return show('Ссылка недействительна','Попросите пекарню показать новый QR-код.');if(!session?.access_token)return show('Нужно войти в кабинет ресторана','После входа снова отсканируйте QR-код.','<a class="button login" href="index.html">Войти</a>');if(!navigator.onLine)return show('Нет подключения к интернету','Для первого открытия QR-кода нужна безопасная проверка. Повторите после появления сети.');root.innerHTML='<p class="loading">Проверяем защищённый код…</p>';try{await flush();const rows=await rpc('panora_delivery_confirmation',{p_token:token});if(!rows?.length)return show('Поставка недоступна','QR-код относится к другому ресторану, недействителен или истёк.');render(rows[0])}catch{show('Нет связи с сервером','Попробуйте снова после появления интернета.')}}
  addEventListener('online',()=>{flush().then(load)});load();
})();
