(function(){
 const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(standalone||localStorage.getItem('panora-install-hint-closed'))return;
 let installPrompt=null;const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);
 const banner=document.createElement('aside');banner.className='install-banner';banner.innerHTML='<div><strong>Panora на домашнем экране</strong><span>Открывайте приложение одним нажатием.</span></div><button class="install-now" type="button">Установить</button><button class="install-dismiss" type="button" aria-label="Закрыть">×</button>';document.body.appendChild(banner);
 const modal=document.createElement('section');modal.className='install-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="install-card"><button class="install-close" type="button" aria-label="Закрыть">×</button><span class="kicker">PANORA</span><h2>Добавить на домашний экран</h2><div class="install-ios"><h3>iPhone или iPad</h3><ol><li>Откройте Panora именно в <strong>Safari</strong>.</li><li>Нажмите кнопку <strong>Поделиться</strong> — квадрат со стрелкой вверх.</li><li>Прокрутите меню и выберите <strong>На экран «Домой»</strong>.</li><li>Нажмите <strong>Добавить</strong>.</li></ol></div><div class="install-android"><h3>Android</h3><ol><li>Откройте Panora в <strong>Chrome</strong>.</li><li>Нажмите меню <strong>⋮</strong> справа сверху.</li><li>Выберите <strong>Установить приложение</strong> или <strong>Добавить на главный экран</strong>.</li><li>Подтвердите установку.</li></ol></div><button class="button button-primary full install-native" type="button">Установить приложение</button></div>`;document.body.appendChild(modal);
 const open=()=>{modal.setAttribute('aria-hidden','false');document.body.classList.add('install-open')},close=()=>{modal.setAttribute('aria-hidden','true');document.body.classList.remove('install-open')};
 banner.querySelector('.install-now').onclick=()=>installPrompt?modal.querySelector('.install-native').click():open();banner.querySelector('.install-dismiss').onclick=()=>{localStorage.setItem('panora-install-hint-closed','1');banner.remove()};modal.querySelector('.install-close').onclick=close;modal.onclick=event=>{if(event.target===modal)close()};
 modal.querySelector('.install-ios').hidden=!ios;modal.querySelector('.install-android').hidden=ios;const native=modal.querySelector('.install-native');native.hidden=true;
 window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;native.hidden=false;banner.querySelector('.install-now').textContent='Установить'});
 native.onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;close()};window.addEventListener('appinstalled',()=>{banner.remove();close()});
})();
