(()=>{
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const productName=id=>{
    const lang=document.querySelector('#adminLanguage')?.value||'ru';
    const product=typeof productRegistry!=='undefined'&&productRegistry.find(item=>item.id===id);
    return product?.names?.[lang]||product?.names?.ru||(id==='plain'?'Льняной бездрожжевой хлеб с семенами':'Тыквенный бездрожжевой хлеб с семенами');
  };
  window.printNote=function(orderId){
    const note=deliveryNotes.find(item=>item.orderId===orderId),order=orders.find(item=>item.id===orderId);
    if(!note){alert('Накладная для этого заказа не найдена.');return}
    const client=restaurant(note.restaurantId)||{},bakery={...(typeof invoiceDefaults!=='undefined'?invoiceDefaults:{}),...bakerySettings,...(note.bakery||{})};
    const prefix=bakery.notePrefix||'DN-',number=`${prefix}${String(note.number).padStart(4,'0')}`;
    window.panoraRecalculateBalances?.();
    const paidHere=Number(note.paidAtShipment??payments.filter(item=>item.deliveryNoteId===note.id&&item.confirmed!==false&&item.status!=='cancelled'&&item.disputeStatus!=='open'&&!/\[panora:b2b-return-credit:[^\]]+\]/.test(String(item.note||''))&&String(item.date||'')===String(note.date||'')).reduce((sum,item)=>sum+Number(item.amount||0),0));
    const before=Math.max(0,Number(note.balanceBefore||0));
    const balance=Math.max(0,Number(note.balanceAfter??(before+Number(note.total||0)-paidHere)));
    document.querySelector('#invoicePreviewDialog')?.remove();
    const dialog=document.createElement('dialog');dialog.id='invoicePreviewDialog';dialog.className='invoice-preview-dialog';
    const followup=window.panoraDeliveryFollowup?.meta?.(note)||{};
    const fmtAt=value=>{if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'})};
    let receiptHtml='<section class="invoice-receipt is-pending"><div><span>Подтверждение получения</span><strong>Ожидает подтверждения партнёра</strong></div><p>Поставка отгружена, но подтверждение получения ещё не зафиксировано.</p></section>';
    if(note.customerConfirmedAt){
      receiptHtml=`<section class="invoice-receipt is-confirmed"><div><span>Подтверждение получения</span><strong>✓ Подтверждено партнёром</strong></div><dl><div><dt>Получатель</dt><dd>${esc(note.customerReceiver||client.name||'Партнёр')}</dd></div><div><dt>Дата и время</dt><dd>${esc(fmtAt(note.customerConfirmedAt))}</dd></div></dl></section>`;
    }else if(note.offlineProof?.receivedAt){
      receiptHtml=`<section class="invoice-receipt is-signed"><div><span>Подтверждение получения</span><strong>✓ Получено по подписи</strong></div><div class="invoice-receipt-grid"><dl><div><dt>Получатель</dt><dd>${esc(note.offlineProof.receiver||'—')}</dd></div><div><dt>Дата и время</dt><dd>${esc(fmtAt(note.offlineProof.receivedAt))}</dd></div></dl>${note.offlineProof.signature?`<figure><figcaption>Подпись получателя</figcaption><img src="${esc(note.offlineProof.signature)}" alt="Подпись получателя"></figure>`:''}</div></section>`;
    }else if(followup.manualClosedAt){
      receiptHtml=`<section class="invoice-receipt is-manual"><div><span>Подтверждение получения</span><strong>Закрыто пекарней</strong></div><dl><div><dt>Основание</dt><dd>${esc(followup.manualReason||'—')}</dd></div><div><dt>Дата и время</dt><dd>${esc(fmtAt(followup.manualClosedAt))}</dd></div>${followup.manualComment?`<div><dt>Комментарий</dt><dd>${esc(followup.manualComment)}</dd></div>`:''}</dl><p class="invoice-receipt-warning">Это административное закрытие, а не подтверждение партнёром.</p></section>`;
    }
    dialog.innerHTML=`<div class="invoice-preview-toolbar"><strong>Накладная ${esc(number)}</strong><button type="button" class="invoice-preview-x" aria-label="Закрыть">×</button></div><article class="invoice-sheet"><header><div><h1>Panora</h1><p><strong>${esc(bakery.legalName||'Panora')}</strong><br>${esc(bakery.taxId||'')}<br>${esc(bakery.address||'')}<br>${esc(bakery.email||'')} ${esc(bakery.phone||'')}</p></div><div class="invoice-document"><h2>${esc(bakery.noteTitle||'Накладная')}</h2><strong>${esc(number)}</strong><span>${esc(note.date)}</span></div></header><section class="invoice-meta"><p><span>Партнёр</span><strong>${esc(client.name||'—')}</strong><br>${esc(client.address||'—')}</p><p><span>Выпечка</span><strong>${esc(order?.date||note.date)}</strong><br><span>Доставка</span> <strong>${esc(order?.deliveryDate||order?.date||note.date)}</strong></p></section><div class="invoice-lines"><div class="invoice-line invoice-line-head"><span>Товар</span><span>Количество</span><span>Цена</span><span>Сумма</span></div>${note.items.map(item=>`<div class="invoice-line"><strong>${esc(productName(item.product))}</strong><span>${esc(item.quantity)} шт.</span><span>${esc(euro(note.prices[item.product]))}</span><strong>${esc(euro(item.quantity*note.prices[item.product]))}</strong></div>`).join('')}</div><section class="invoice-totals"><p><span>Итого</span><strong>${esc(euro(note.total))}</strong></p><p><span>Задолженность до поставки</span><strong>${esc(euro(before))}</strong></p><p><span>Оплачено при отгрузке</span><strong>${esc(euro(paidHere))}</strong></p><p class="invoice-balance"><span>Задолженность после операции</span><strong>${esc(euro(balance))}</strong></p></section><section class="invoice-trays"><h3>Возвратные лотки</h3><p><span>Передано с поставкой</span><strong>${esc(Number(note.traysDelivered||0))} шт.</strong></p><p><span>Возвращено партнёром</span><strong>${esc(Number(note.traysReturned||0))} шт.</strong></p><p><span>Осталось у партнёра</span><strong>${esc(Number(note.trayBalanceAfter||0))} шт.</strong></p></section>${receiptHtml}${bakery.paymentTerms?`<p class="invoice-note"><strong>Условия оплаты:</strong> ${esc(bakery.paymentTerms)}</p>`:''}${bakery.noteFooter?`<p class="invoice-note">${esc(bakery.noteFooter)}</p>`:''}<footer><span>${esc(bakery.bakerySignature||'Panora')} __________________</span><span>${esc(bakery.customerSignature||'Партнёр')} __________________</span></footer></article><div class="invoice-preview-actions"><button type="button" class="secondary invoice-preview-close">Закрыть</button><button type="button" class="secondary invoice-preview-accounting">Библиотека документов</button><button type="button" class="primary invoice-preview-print">Печать / PDF</button></div>`;
    document.body.appendChild(dialog);
    const close=()=>dialog.close();dialog.querySelector('.invoice-preview-x').onclick=close;dialog.querySelector('.invoice-preview-close').onclick=close;dialog.querySelector('.invoice-preview-accounting').onclick=()=>window.openPanoraDocumentLibrary?.(note,{context:'admin'});dialog.querySelector('.invoice-preview-print').onclick=()=>window.print();dialog.onclick=event=>{if(event.target===dialog)close()};dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();
  };
})();
