let account=null;
const portalRead=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const portalMoney=n=>new Intl.NumberFormat(I18N[lang].locale,{style:'currency',currency:'EUR'}).format(Number(n)||0);
function portalRestaurants(){return portalRead('panora-restaurants')}
function portalOrders(){return portalRead('panora-orders')}
function portalNotes(){return portalRead('panora-delivery-notes')}
function portalPayments(){return portalRead('panora-payments')}
function accountDebt(){const shipped=portalNotes().filter(n=>n.restaurantId===account.id).reduce((s,n)=>s+n.total,0),paid=portalPayments().filter(p=>p.restaurantId===account.id).reduce((s,p)=>s+p.amount,0);return shipped-paid}
function accountText(key){const x={ru:{login:'Вход для ресторана',email:'Email',code:'Код доступа',enter:'Войти',error:'Неверный email или код доступа',debt:'Текущая задолженность',prices:'Ваши цены',orders:'Заказы',noOrders:'Заказов пока нет',logout:'Выйти',close:'Закрыть',plain:'Обычный хлеб',pumpkin:'Хлеб из тыквы',piece:'за 1 шт.',shipped:'Отгружен',confirmed:'Подтверждён'},en:{login:'Restaurant sign in',email:'Email',code:'Access code',enter:'Sign in',error:'Incorrect email or access code',debt:'Current balance due',prices:'Your prices',orders:'Orders',noOrders:'No orders yet',logout:'Sign out',close:'Close',plain:'Plain bread',pumpkin:'Pumpkin bread',piece:'per piece',shipped:'Shipped',confirmed:'Confirmed'},es:{login:'Acceso para restaurantes',email:'Email',code:'Código de acceso',enter:'Entrar',error:'Email o código incorrecto',debt:'Deuda actual',prices:'Tus precios',orders:'Pedidos',noOrders:'Aún no hay pedidos',logout:'Salir',close:'Cerrar',plain:'Pan clásico',pumpkin:'Pan de calabaza',piece:'por unidad',shipped:'Enviado',confirmed:'Confirmado'}};return x[lang][key]}
function checkoutLabel(){return account?tr('cart.checkout'):(lang==='ru'?'Войти и оформить заказ':lang==='es'?'Entrar y realizar pedido':'Sign in to order')}
function updateCheckoutAccess(){$('#checkoutButton').textContent=checkoutLabel();$('#profileButton').classList.toggle('account-active',Boolean(account));$('#profileButton').title=account?account.name:accountText('login')}
function restoreAccount(){const id=localStorage.getItem('panora-account-id');account=portalRestaurants().find(r=>r.id===id)||null;if(account)applyAccount()}
function applyAccount(){SHOW_PRICES=true;PRODUCTS.find(p=>p.id==='plain').price=Number(account.prices.plain);PRODUCTS.find(p=>p.id==='pumpkin').price=Number(account.prices.pumpkin);const f=$('#checkoutForm');f.restaurant.value=account.name;f.restaurant.readOnly=true;f.email.value=account.email;f.email.readOnly=true;f.phone.value=account.phone||'';f.address.value=account.address||'';renderProducts();renderCart();renderAccountModal();updateCheckoutAccess()}
function renderAccountModal(){const modal=$('#profileModal');if(!account){modal.innerHTML=`<div class="modal-head"><div><span class="kicker">Panora</span><h2>${accountText('login')}</h2></div><button class="close-button" data-portal-close>×</button></div><form class="account-login" id="accountLogin"><label><span>${accountText('email')}</span><input name="email" type="email" required autocomplete="email"></label><label><span>${accountText('code')}</span><input name="code" required autocomplete="current-password"></label><p class="account-error" id="accountError">${accountText('error')}</p><button class="button button-primary full">${accountText('enter')}</button></form>`;modal.querySelector('[data-portal-close]').onclick=closePanels;modal.querySelector('#accountLogin').onsubmit=loginAccount;return}const orders=portalOrders().filter(o=>o.restaurantId===account.id).slice().reverse();modal.innerHTML=`<div class="modal-head"><div><span class="kicker">Panora</span><h2>${tr('profile.title')}</h2></div><button class="close-button" data-portal-close>×</button></div><div class="account-head"><div class="account-avatar">${account.name[0].toUpperCase()}</div><div><strong>${account.name}</strong><span>${account.email}</span></div></div><div class="account-balance"><span>${accountText('debt')}</span><strong>${portalMoney(accountDebt())}</strong></div><section class="account-section"><h3>${accountText('prices')}</h3><div class="account-price"><span>${accountText('plain')}<small>${accountText('piece')}</small></span><strong>${portalMoney(account.prices.plain)}</strong></div><div class="account-price"><span>${accountText('pumpkin')}<small>${accountText('piece')}</small></span><strong>${portalMoney(account.prices.pumpkin)}</strong></div></section><section class="account-section"><h3>${accountText('orders')}</h3>${orders.length?orders.map(o=>`<div class="account-order"><span><strong>PN-${String(o.number).padStart(4,'0')}</strong><small>${o.date} · ${o.items.reduce((s,i)=>s+i.quantity,0)} ${lang==='ru'?'шт.':lang==='es'?'uds.':'pcs'}</small></span><span>${o.status==='shipped'?accountText('shipped'):accountText('confirmed')}</span></div>`).join(''):`<p>${accountText('noOrders')}</p>`}</section><div class="account-actions"><button class="button button-ghost" id="accountLogout">${accountText('logout')}</button><button class="button button-primary" data-portal-close>${accountText('close')}</button></div>`;modal.querySelectorAll('[data-portal-close]').forEach(b=>b.onclick=closePanels);modal.querySelector('#accountLogout').onclick=logoutAccount}
function loginAccount(e){e.preventDefault();const f=new FormData(e.target),email=String(f.get('email')).trim().toLowerCase(),code=String(f.get('code')).trim(),found=portalRestaurants().find(r=>r.email.toLowerCase()===email&&String(r.accessCode)===code);if(!found){$('#accountError').classList.add('show');return}account=found;localStorage.setItem('panora-account-id',account.id);applyAccount();showToast(account.name)}
function logoutAccount(){account=null;SHOW_PRICES=false;PRODUCTS.forEach(p=>p.price=0);localStorage.removeItem('panora-account-id');const f=$('#checkoutForm');f.restaurant.value='';f.restaurant.readOnly=false;f.email.value='';f.email.readOnly=false;renderProducts();renderCart();renderAccountModal();updateCheckoutAccess()}
function portalStatus(status){const labels={ru:{submitted:'Получен',confirmed:'Подтверждён',shipped:'Отгружен',cancelled:'Отменён'},en:{submitted:'Received',confirmed:'Confirmed',shipped:'Shipped',cancelled:'Cancelled'},es:{submitted:'Recibido',confirmed:'Confirmado',shipped:'Enviado',cancelled:'Cancelado'}};return labels[lang][status]||status}
function canRestaurantCancel(order){if(!['submitted','confirmed'].includes(order.status))return false;const plan=productionPlans().find(p=>p.bakeDate===order.date&&order.items.some(i=>i.product===p.product));return !plan||new Date(plan.cutoff)>new Date()}
function restaurantCancelOrder(id){const orders=portalRead('panora-orders'),order=orders.find(o=>o.id===id);if(!order||!canRestaurantCancel(order))return;const question=lang==='ru'?'Отменить заказ?':lang==='es'?'¿Cancelar el pedido?':'Cancel this order?';if(!confirm(question))return;order.status='cancelled';const plans=productionPlans();order.items.forEach(i=>{const p=plans.find(x=>x.bakeDate===order.date&&x.product===i.product);if(p)p.ordered=Math.max(0,Number(p.ordered||0)-i.quantity)});localStorage.setItem('panora-orders',JSON.stringify(orders));localStorage.setItem('panora-production-plans',JSON.stringify(plans));renderAccountModal();renderProducts();renderCart()}
const baseRenderAccountModal=renderAccountModal;renderAccountModal=function(){baseRenderAccountModal();if(!account)return;const current=portalOrders().filter(o=>o.restaurantId===account.id).slice().reverse(),rows=[...document.querySelectorAll('.account-order')];rows.forEach((row,index)=>{const order=current[index],right=row.lastElementChild;if(!order||!right)return;const cancel=lang==='ru'?'Отменить':lang==='es'?'Cancelar':'Cancel';right.innerHTML=`<span class="account-status">${portalStatus(order.status)}</span>${canRestaurantCancel(order)?`<button class="account-cancel" data-account-cancel="${order.id}">${cancel}</button>`:''}`});document.querySelectorAll('[data-account-cancel]').forEach(b=>b.onclick=()=>restaurantCancelOrder(b.dataset.accountCancel))}
function enforceDateConfirmation(){const confirmBox=$('#confirmDeliveryDate'),button=$('#checkoutButton'),count=cartData().count;if(!count)confirmBox.checked=false;button.disabled=count<MIN_PIECES||!confirmBox.checked}
const baseRenderCart=renderCart;renderCart=function(){baseRenderCart();enforceDateConfirmation()};
document.addEventListener('change',e=>{if(e.target.id==='confirmDeliveryDate')enforceDateConfirmation();if(e.target.id==='cartDeliveryDate'){$('#confirmDeliveryDate').checked=false;enforceDateConfirmation()}},true);
const originalApplyLanguage=applyLanguage;applyLanguage=function(){originalApplyLanguage();renderAccountModal();updateCheckoutAccess()};
const originalShowShare=showShare;showShare=function(order){if(account){const orders=portalOrders();if(!orders.some(o=>o.sourceId===order.id)){const plans=productionPlans(),schedule=plans.find(x=>x.bakeDate===order.date),settings=portalRead('panora-bakery-settings',{taxRate:0});const saved={id:crypto.randomUUID(),sourceId:order.id,number:(orders.at(-1)?.number||0)+1,restaurantId:account.id,date:order.date,deliveryDate:schedule?.deliveryDate||order.date,items:order.items.map(i=>({product:i.id,quantity:i.quantityPieces})),prices:structuredClone(account.prices),taxRate:Number(settings.taxRate||0),status:'submitted'};orders.push(saved);localStorage.setItem('panora-orders',JSON.stringify(orders));saved.items.forEach(i=>{const p=plans.find(x=>x.bakeDate===saved.date&&x.product===i.product);if(p)p.ordered=Number(p.ordered||0)+i.quantity});localStorage.setItem('panora-production-plans',JSON.stringify(plans))}renderAccountModal()}originalShowShare(order)};
const originalCheckout=$('#checkoutButton').onclick;$('#checkoutButton').onclick=()=>{if(!$('#confirmDeliveryDate').checked){showToast(lang==='ru'?'Подтвердите дату поставки':lang==='es'?'Confirma la fecha de entrega':'Confirm the delivery date');return}if(!account){closePanels();setTimeout(()=>openPanel($('#profileModal')),180);return}originalCheckout()};
$('#checkoutForm').addEventListener('submit',e=>{if(!account){e.preventDefault();e.stopImmediatePropagation();closePanels();setTimeout(()=>openPanel($('#profileModal')),180);return}const schedules=productionPlans().filter(p=>p.bakeDate===selectedBakeDate&&Object.keys(cart).includes(p.product)),closed=schedules.some(p=>!p.open||new Date(p.cutoff)<=new Date()),unavailable=Object.entries(cart).find(([id,qty])=>qty>availablePieces(id));if(closed||unavailable){e.preventDefault();e.stopImmediatePropagation();alert(closed?(lang==='ru'?'Приём заказов на эту выпечку уже закрыт.':lang==='es'?'Los pedidos para este horneado están cerrados.':'Orders for this bake are closed.'):(lang==='ru'?'Количество изменилось. Проверьте доступный остаток.':lang==='es'?'La cantidad disponible ha cambiado. Revísala.':'Available quantity has changed. Please review it.'));renderBakeDates();renderProducts();renderCart()}},true);
restoreAccount();renderAccountModal();updateCheckoutAccess();renderCart();
