const productRegistryDefaults=[
 {id:'plain',builtIn:true,active:true,weight:750,basePrice:4.5,image:'bread-plain.jpg',names:{ru:'Льняной бездрожжевой хлеб с семенами',en:'Yeast-free flaxseed bread with seeds',es:'Pan de lino sin levadura con semillas'},descriptions:{ru:'Бездрожжевой льняной хлеб с семенами.',en:'Yeast-free flaxseed bread with seeds.',es:'Pan de lino sin levadura con semillas.'}},
 {id:'pumpkin',builtIn:true,active:true,weight:750,basePrice:5,image:'bread-pumpkin.jpg',names:{ru:'Тыквенный бездрожжевой хлеб с семенами',en:'Yeast-free pumpkin bread with seeds',es:'Pan de calabaza sin levadura con semillas'},descriptions:{ru:'Бездрожжевой тыквенный хлеб с семенами.',en:'Yeast-free pumpkin bread with seeds.',es:'Pan de calabaza sin levadura con semillas.'}}
];
let productRegistry=cRead('panora-products',productRegistryDefaults);
if(!productRegistry.some(p=>p.id==='plain'))productRegistry=[...productRegistryDefaults,...productRegistry];
if(localStorage.getItem('panora-builtin-products-version')!=='3'){
 productRegistryDefaults.forEach(source=>{const target=productRegistry.find(p=>p.id===source.id);if(target)Object.assign(target,structuredClone(source));else productRegistry.push(structuredClone(source))});
 const savedRestaurants=JSON.parse(localStorage.getItem('panora-restaurants')||'[]');
 savedRestaurants.forEach(r=>{r.prices??={};r.prices.plain=4.5;r.prices.pumpkin=5});
 localStorage.setItem('panora-products',JSON.stringify(productRegistry));
 localStorage.setItem('panora-restaurants',JSON.stringify(savedRestaurants));
 localStorage.setItem('panora-builtin-products-version','3');
 if(typeof restaurants!=='undefined')restaurants=savedRestaurants;
}
const productLabel=(id,language=lang)=>productRegistry.find(p=>p.id===id)?.names?.[language]||productRegistry.find(p=>p.id===id)?.names?.ru||id;
productName=id=>productLabel(id);
function saveProducts(){cSave('panora-products',productRegistry);window.panoraCloud?.queueProducts()}
function fileData(file){return new Promise(resolve=>{if(!file)return resolve('');const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const size=900,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);resolve(canvas.toDataURL('image/webp',.84))};img.onerror=()=>resolve(reader.result);img.src=reader.result};reader.readAsDataURL(file)})}
const productEscape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
document.body.insertAdjacentHTML('beforeend',`<dialog id="productEditDialog" class="product-edit-dialog"><form method="dialog" id="productEditForm"><button type="button" class="dialog-close" id="closeProductEdit" aria-label="Закрыть">×</button><h3 id="productEditTitle">Карточка продукции</h3><input type="hidden" name="productId"><div class="product-photo-editor"><img id="productPhotoPreview" alt="Предпросмотр фотографии"><div><label><span>Фотография хлеба</span><input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" class="secondary" id="removeProductPhoto">Удалить фотографию</button><small>Рекомендуется квадратное фото JPG или WebP.</small></div></div><div class="settings-row"><label><span>Название RU</span><input name="nameRu" required></label><label><span>Название EN</span><input name="nameEn" required></label></div><label><span>Название ES</span><input name="nameEs" required></label><label><span>Описание RU</span><textarea name="descRu" rows="2"></textarea></label><label><span>Описание EN</span><textarea name="descEn" rows="2"></textarea></label><label><span>Описание ES</span><textarea name="descEs" rows="2"></textarea></label><div class="settings-row"><label><span>Вес одной штуки, г</span><input name="weight" type="number" min="1" required></label><label><span>Базовая цена, €</span><input name="basePrice" type="number" min="0" step="0.01" required><small>Цены ресторанов настраиваются отдельно.</small></label></div><label class="check"><input name="active" type="checkbox"><span>Показывать в каталоге ресторанов</span></label><div class="dialog-actions"><button type="button" id="cancelProductEdit">Отмена</button><button type="submit" class="primary">Сохранить карточку</button></div></form></dialog>`);
let removeEditedPhoto=false;
function renderProductCards(){const grid=document.querySelector('#productAdminGrid');if(!grid)return;grid.innerHTML=productRegistry.map(p=>`<article class="product-admin-card"><div class="product-admin-photo"><img src="${productEscape(p.image||'icon.svg')}" alt="${productEscape(p.names?.ru)}"><span class="product-status ${p.active===false?'off':''}">${p.active===false?'Скрыт':'В каталоге'}</span></div><div class="product-admin-body"><h3>${productEscape(p.names?.ru)}</h3><p>${productEscape(p.descriptions?.ru||'Описание не заполнено')}</p><dl><div><dt>Вес</dt><dd>${Number(p.weight)||0} г</dd></div><div><dt>Базовая цена</dt><dd>${Number(p.basePrice||0).toFixed(2)} €</dd></div></dl><button type="button" class="primary" data-edit-product="${p.id}">Настроить карточку</button></div></article>`).join('');grid.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>openProductEditor(b.dataset.editProduct))}
function openProductEditor(id=''){const p=productRegistry.find(x=>x.id===id),form=document.querySelector('#productEditForm');form.reset();form.productId.value=p?.id||'';form.nameRu.value=p?.names?.ru||'';form.nameEn.value=p?.names?.en||'';form.nameEs.value=p?.names?.es||'';form.descRu.value=p?.descriptions?.ru||'';form.descEn.value=p?.descriptions?.en||'';form.descEs.value=p?.descriptions?.es||'';form.weight.value=p?.weight||750;form.basePrice.value=p?.basePrice||0;form.active.checked=p?.active!==false;form.photo.value='';removeEditedPhoto=false;document.querySelector('#productEditTitle').textContent=p?'Настроить карточку':'Новый вид хлеба';document.querySelector('#productPhotoPreview').src=p?.image||'icon.svg';document.querySelector('#productEditDialog').showModal()}
function closeProductEditor(){document.querySelector('#productEditDialog').close()}
document.querySelector('#closeProductEdit').onclick=closeProductEditor;
document.querySelector('#cancelProductEdit').onclick=closeProductEditor;
document.querySelector('#productEditDialog').onclick=e=>{if(e.target===e.currentTarget)closeProductEditor()};
document.querySelector('#removeProductPhoto').onclick=()=>{removeEditedPhoto=true;document.querySelector('#productEditForm').photo.value='';document.querySelector('#productPhotoPreview').src='icon.svg'};
document.querySelector('#productEditForm').photo.onchange=e=>{const file=e.target.files[0];if(!file)return;removeEditedPhoto=false;const reader=new FileReader();reader.onload=()=>document.querySelector('#productPhotoPreview').src=reader.result;reader.readAsDataURL(file)};
document.querySelector('#productEditForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form),id=f.get('productId')||`bread-${Date.now()}`;let p=productRegistry.find(x=>x.id===id);if(!p){p={id,active:true,builtIn:false};productRegistry.push(p);recipes[id]=[];restaurants.forEach(r=>{r.prices??={};r.prices[id]=Number(f.get('basePrice')||0)});cSave('panora-restaurants',restaurants)}const uploaded=await fileData(form.photo.files[0]);p.names={ru:f.get('nameRu'),en:f.get('nameEn'),es:f.get('nameEs')};p.descriptions={ru:f.get('descRu'),en:f.get('descEn'),es:f.get('descEs')};p.weight=Number(f.get('weight'));p.basePrice=Number(f.get('basePrice'));p.active=f.get('active')==='on';if(uploaded)p.image=uploaded;else if(removeEditedPhoto)p.image=p.id==='plain'?'bread-plain.jpg':p.id==='pumpkin'?'bread-pumpkin.jpg':'icon.svg';saveProducts();store('panora-recipes',recipes);closeProductEditor();renderProductCards();renderAll();renderProductManagement()};
document.querySelector('#addProductCard').onclick=()=>openProductEditor();
const recipeHead=document.querySelector('#view-recipes .page-head');
recipeHead.insertAdjacentHTML('beforeend','<button class="primary" id="addBreadType">+ Новый вид хлеба</button>');
document.body.insertAdjacentHTML('beforeend',`<dialog id="breadTypeDialog"><form method="dialog" id="breadTypeForm"><h3>Новый вид хлеба</h3><div class="settings-row"><label><span>Название RU</span><input name="nameRu" required></label><label><span>Название EN</span><input name="nameEn" required></label></div><label><span>Название ES</span><input name="nameEs" required></label><div class="settings-row"><label><span>Вес, г</span><input name="weight" type="number" min="1" value="600" required></label><label><span>Базовая цена, €</span><input name="basePrice" type="number" min="0" step="0.01" value="0"></label></div><label><span>Описание RU</span><input name="descRu"></label><label><span>Описание EN</span><input name="descEn"></label><label><span>Описание ES</span><input name="descEs"></label><label><span>Фотография карточки</span><input name="photo" type="file" accept="image/*"></label><label class="check"><input name="active" type="checkbox" checked><span>Показывать в каталоге</span></label><div class="dialog-actions"><button value="cancel">Отмена</button><button class="primary" id="saveBreadType">Создать хлеб и рецепт</button></div></form></dialog>`);
document.querySelector('#addBreadType').onclick=()=>document.querySelector('#breadTypeDialog').showModal();
document.querySelector('#saveBreadType').onclick=async e=>{e.preventDefault();const form=document.querySelector('#breadTypeForm'),f=new FormData(form),id=`bread-${Date.now()}`,image=await fileData(form.photo.files[0]);productRegistry.push({id,active:f.get('active')==='on',weight:Number(f.get('weight')||600),basePrice:Number(f.get('basePrice')||0),image,names:{ru:f.get('nameRu'),en:f.get('nameEn'),es:f.get('nameEs')},descriptions:{ru:f.get('descRu')||'',en:f.get('descEn')||'',es:f.get('descEs')||''}});recipes[id]=[];saveProducts();store('panora-recipes',recipes);form.reset();document.querySelector('#breadTypeDialog').close();renderAll();renderProductManagement()};
function renderProductManagement(){document.querySelectorAll('.product-manage').forEach(x=>x.remove());document.querySelectorAll('.recipe-card').forEach((card,index)=>{const p=productRegistry[index];if(!p)return;card.insertAdjacentHTML('beforeend',`<div class="product-manage"><label><input type="checkbox" data-product-active="${p.id}" ${p.active!==false?'checked':''}> В каталоге</label>${p.builtIn?'':`<button type="button" data-delete-product="${p.id}">Удалить вид хлеба</button>`}</div>`)});document.querySelectorAll('[data-product-active]').forEach(x=>x.onchange=()=>{productRegistry.find(p=>p.id===x.dataset.productActive).active=x.checked;saveProducts()});document.querySelectorAll('[data-delete-product]').forEach(b=>b.onclick=()=>{const p=productRegistry.find(x=>x.id===b.dataset.deleteProduct);if(!confirm(`Удалить «${p.names.ru}»?`))return;productRegistry=productRegistry.filter(x=>x.id!==p.id);delete recipes[p.id];saveProducts();store('panora-recipes',recipes);renderAll();renderProductManagement()})}
const originalRenderRecipes=renderRecipes;renderRecipes=function(){originalRenderRecipes();renderProductManagement()};
function buildPlanProductFields(){const box=document.querySelector('.bread-plan-fields');box.innerHTML='<legend>Количество хлеба, шт.</legend>'+productRegistry.filter(p=>p.active!==false).map(p=>`<label><span>${productLabel(p.id)}</span><input type="number" min="0" max="5000" step="1" placeholder="Количество" data-plan-product="${p.id}"></label>`).join('')}
const originalAddPlan=document.querySelector('#addPlan').onclick;document.querySelector('#addPlan').onclick=()=>{buildPlanProductFields();originalAddPlan()};
document.querySelector('#savePlan').onclick=e=>{e.preventDefault();const form=document.querySelector('#planForm'),f=new FormData(form),amounts=[...form.querySelectorAll('[data-plan-product]')].map(i=>[i.dataset.planProduct,Number(i.value||0)]);if(!amounts.some(([,n])=>n)){alert('Укажите количество хотя бы одного хлеба.');return}amounts.forEach(([product,planned])=>{if(!planned)return;const existing=plans.find(p=>p.bakeDate===f.get('bakeDate')&&p.product===product);if(existing)Object.assign(existing,{deliveryDate:f.get('deliveryDate'),planned,cutoff:f.get('cutoff'),open:f.get('open')==='on'});else plans.push({id:crypto.randomUUID(),bakeDate:f.get('bakeDate'),deliveryDate:f.get('deliveryDate'),product,planned,ordered:0,cutoff:f.get('cutoff'),open:f.get('open')==='on'})});store('panora-production-plans',plans);document.querySelector('#planDialog').close();renderAll()};
function syncProductSelects(){['#movementForm select[name="product"]'].forEach(sel=>{const el=document.querySelector(sel);if(el)el.innerHTML=productRegistry.filter(p=>p.active!==false).map(p=>`<option value="${p.id}">${productLabel(p.id)}</option>`).join('')})}
function customProducts(){return productRegistry.filter(p=>!p.builtIn&&p.active!==false)}
function addCustomRestaurantFields(){const form=document.querySelector('#restaurantForm'),actions=form.querySelector('.dialog-actions');form.querySelectorAll('[data-new-product-price]').forEach(x=>x.remove());customProducts().forEach(p=>actions.insertAdjacentHTML('beforebegin',`<label data-new-product-price><span>${productLabel(p.id)} — цена, € / шт.</span><input name="price_${p.id}" type="number" min="0" step="0.01" value="${p.basePrice||0}" required></label>`))}
const baseAddRestaurant=document.querySelector('#addRestaurant').onclick;document.querySelector('#addRestaurant').onclick=()=>{addCustomRestaurantFields();baseAddRestaurant()};
document.querySelector('#saveRestaurant').onclick=e=>{e.preventDefault();const form=document.querySelector('#restaurantForm'),f=new FormData(form),prices={plain:Number(f.get('plainPrice')),pumpkin:Number(f.get('pumpkinPrice'))};customProducts().forEach(p=>prices[p.id]=Number(f.get(`price_${p.id}`)||p.basePrice||0));restaurants.push({id:crypto.randomUUID(),name:f.get('name'),email:f.get('email'),accessCode:f.get('accessCode'),phone:f.get('phone'),telegram:String(f.get('telegram')||'').replace('@',''),language:f.get('language')||'ru',address:f.get('address'),prices});cSave('panora-restaurants',restaurants);document.querySelector('#restaurantDialog').close();form.reset();renderCommerce()};
const baseRenderRestaurants=renderRestaurants;renderRestaurants=function(){baseRenderRestaurants();const active=activeRestaurants(),cards=[...document.querySelectorAll('.restaurant-card')];cards.forEach((card,index)=>{const r=active[index],debt=card.querySelector('.debt-row');if(!r||!debt)return;customProducts().forEach(p=>{if(card.querySelector(`[data-price="${r.id}:${p.id}"]`))return;debt.insertAdjacentHTML('beforebegin',`<label class="price-row"><span>${productLabel(p.id)}</span><span><input data-custom-price="${r.id}:${p.id}" type="number" min="0" step="0.01" value="${Number(r.prices[p.id]??p.basePrice??0).toFixed(2)}"> €</span></label>`)});});document.querySelectorAll('[data-custom-price]').forEach(i=>i.onchange=()=>{const [id,pid]=i.dataset.customPrice.split(':');restaurant(id).prices[pid]=Number(i.value);cSave('panora-restaurants',restaurants)})};
function orderLine(order,item){const prices=order.prices||restaurant(order.restaurantId)?.prices||{},price=Number(prices[item.product]||0),total=price*Number(item.quantity||0);return `<div class="order-price-line"><strong>${productLabel(item.product)}</strong><span>${item.quantity} шт. × ${euro(price)} = <b>${euro(total)}</b></span></div>`}
function orderStatusClass(status){return{submitted:'tag-new-order',confirmed:'tag-confirmed-order',shipped:'tag-shipped-order',cancelled:'tag-cancelled-order'}[status]||''}
renderOrders=function(){const body=document.querySelector('#orderRows');body.innerHTML=orders.length?orders.slice().reverse().map(o=>`<tr class="order-row order-row-${o.status}"><td>PN-${String(o.number).padStart(4,'0')}</td><td><div class="order-dates"><strong>Выпечка: ${o.date}</strong><small>Доставка: ${o.deliveryDate||o.date}</small></div></td><td>${restaurant(o.restaurantId)?.name||'—'}</td><td><div class="order-items">${o.items.map(i=>orderLine(o,i)).join('')}</div></td><td><strong>${euro(orderTotal(o))}</strong></td><td><span class="tag ${orderStatusClass(o.status)}">${orderStatus(o)}</span></td><td class="order-action-cell">${orderActions(o)}</td></tr>`).join(''):'<tr><td class="empty-row" colspan="7">Заказов пока нет.</td></tr>';document.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>openShipment(b.dataset.ship));document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>printNote(b.dataset.note));document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>confirmOrder(b.dataset.confirm));document.querySelectorAll('[data-cancel-order]').forEach(b=>b.onclick=()=>cancelOrder(b.dataset.cancelOrder))};
/* Keep the shipment quantity editor defined in commerce.js. */
function addCustomOrderFields(){const form=document.querySelector('#orderForm'),hint=form.querySelector('.form-hint');form.querySelectorAll('[data-custom-order]').forEach(x=>x.remove());customProducts().forEach(p=>hint.insertAdjacentHTML('beforebegin',`<label data-custom-order><span>${productLabel(p.id)}, шт.</span><input name="qty_${p.id}" type="number" min="0" step="1" placeholder="Количество"></label>`))}
const baseAddOrder=document.querySelector('#addOrder').onclick;document.querySelector('#addOrder').onclick=()=>{addCustomOrderFields();baseAddOrder()};
document.querySelector('#saveOrder').onclick=e=>{e.preventDefault();const form=document.querySelector('#orderForm'),f=new FormData(form),quantities={plain:Number(f.get('plain')||0),pumpkin:Number(f.get('pumpkin')||0)};customProducts().forEach(p=>quantities[p.id]=Number(f.get(`qty_${p.id}`)||0));const items=Object.entries(quantities).filter(([,quantity])=>quantity>0).map(([product,quantity])=>({product,quantity}));if(items.reduce((s,i)=>s+i.quantity,0)<12){alert('Минимальный заказ — 12 шт.');return}const r=restaurant(f.get('restaurant'));orders.push({id:crypto.randomUUID(),number:(orders.at(-1)?.number||0)+1,restaurantId:r.id,date:f.get('date'),deliveryDate:f.get('date'),items,prices:structuredClone(r.prices),taxRate:Number(bakerySettings.taxRate),status:'confirmed'});cSave('panora-orders',orders);syncPlansFromOrders();document.querySelector('#orderDialog').close();form.reset();renderCommerce();renderAll()};
syncProductSelects();renderProductManagement();renderProductCards();renderCommerce();
