/* Panora 9.92 — Retail account: phone OTP + local profile/order index. */
(()=>{
'use strict';
const SESSION_KEY='panora-retail-phone-session-v992';
const PROFILE_KEY='panora-retail-profile-v992';
const ORDERS_KEY='panora-retail-my-orders-v992';
const GUEST_KEY='panora-retail-guest-checkout-v992';
const cfg=window.PANORA_SUPABASE||{};
const $=s=>document.querySelector(s);
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
const lang=()=>{const l=localStorage.getItem('panora-retail-language')||document.documentElement.lang||'es';return ['es','en','de','ru'].includes(l)?l:'es'};
const L={
 es:{login:'Entrar',account:'Mi cuenta',title:'Tu cuenta Panora',intro:'Usa tu teléfono como acceso. Te enviaremos un código SMS de un solo uso.',phone:'Teléfono con prefijo internacional',phoneHint:'Ejemplo: +34 612 345 678',send:'Enviar código',code:'Código SMS',verify:'Confirmar y continuar',sent:'Código enviado. Introdúcelo aquí.',badPhone:'Introduce el teléfono en formato internacional, por ejemplo +34…',badCode:'Introduce el código recibido por SMS.',network:'No se pudo conectar con el servicio SMS.',guest:'Continuar sin cuenta',guestHint:'Si SMS no está disponible, puedes completar este pedido como invitado.',profile:'Mis datos',orders:'Mis pedidos',logout:'Salir',none:'Todavía no hay pedidos guardados en este dispositivo.',verified:'Teléfono confirmado',name:'Nombre',email:'Email · opcional',save:'Guardar datos',saved:'Datos guardados.',order:'Pedido'},
 en:{login:'Sign in',account:'My account',title:'Your Panora account',intro:'Use your phone number to sign in. We will send a one-time SMS code.',phone:'Phone with country code',phoneHint:'Example: +34 612 345 678',send:'Send code',code:'SMS code',verify:'Confirm and continue',sent:'Code sent. Enter it here.',badPhone:'Enter the phone in international format, for example +34…',badCode:'Enter the code received by SMS.',network:'Could not connect to the SMS service.',guest:'Continue without account',guestHint:'If SMS is unavailable, you can complete this order as a guest.',profile:'My details',orders:'My orders',logout:'Sign out',none:'No orders have been saved on this device yet.',verified:'Phone verified',name:'Name',email:'Email · optional',save:'Save details',saved:'Details saved.',order:'Order'},
 de:{login:'Anmelden',account:'Mein Konto',title:'Dein Panora-Konto',intro:'Nutze deine Telefonnummer für den Zugang. Wir senden einen einmaligen SMS-Code.',phone:'Telefon mit Ländervorwahl',phoneHint:'Beispiel: +34 612 345 678',send:'Code senden',code:'SMS-Code',verify:'Bestätigen und weiter',sent:'Code gesendet. Gib ihn hier ein.',badPhone:'Telefon im internationalen Format eingeben, z. B. +34…',badCode:'Gib den SMS-Code ein.',network:'SMS-Dienst ist derzeit nicht erreichbar.',guest:'Ohne Konto fortfahren',guestHint:'Falls SMS nicht verfügbar ist, kannst du diese Bestellung als Gast abschließen.',profile:'Meine Daten',orders:'Meine Bestellungen',logout:'Abmelden',none:'Auf diesem Gerät sind noch keine Bestellungen gespeichert.',verified:'Telefon bestätigt',name:'Name',email:'E-Mail · optional',save:'Daten speichern',saved:'Daten gespeichert.',order:'Bestellung'},
 ru:{login:'Войти',account:'Мои заказы',title:'Ваш аккаунт Panora',intro:'Основной вход — по номеру телефона. Мы отправим одноразовый код по SMS.',phone:'Телефон с кодом страны',phoneHint:'Например: +34 612 345 678',send:'Получить код',code:'Код из SMS',verify:'Подтвердить и продолжить',sent:'Код отправлен. Введите его ниже.',badPhone:'Введите телефон в международном формате, например +34…',badCode:'Введите код из SMS.',network:'Не удалось связаться с сервисом SMS.',guest:'Продолжить без аккаунта',guestHint:'Если SMS временно недоступно, этот заказ можно оформить как гость.',profile:'Мои данные',orders:'Мои заказы',logout:'Выйти',none:'На этом устройстве пока нет сохранённых заказов.',verified:'Телефон подтверждён',name:'Имя',email:'Email · необязательно',save:'Сохранить данные',saved:'Данные сохранены.',order:'Заказ'}
};
const t=k=>(L[lang()]||L.es)[k]||k;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalizePhone=value=>{const raw=String(value||'').trim();const plus=raw.startsWith('+');const digits=raw.replace(/\D/g,'');return plus&&digits.length>=8&&digits.length<=15?`+${digits}`:''};
const session=()=>read(SESSION_KEY,null);
const profile=()=>read(PROFILE_KEY,{});
const orders=()=>read(ORDERS_KEY,[]);
let resumeCheckout=false;
let requestedPhone='';
function ensureUi(){
 if($('#retailAccountButton'))return;
 const actions=$('.top-actions'); if(!actions)return;
 const btn=document.createElement('button');btn.type='button';btn.id='retailAccountButton';btn.className='retail-account-button';btn.addEventListener('click',()=>openAccount(session()?'profile':'login'));actions.prepend(btn);
 const dialog=document.createElement('dialog');dialog.id='retailAccountDialog';dialog.className='retail-account-dialog';dialog.innerHTML=`<div class="retail-account-head"><div><small>PANORA · RETAIL</small><h2 id="retailAccountTitle"></h2></div><button type="button" class="retail-account-close" id="retailAccountClose">×</button></div><div class="retail-account-body" id="retailAccountBody"></div>`;document.body.append(dialog);
 $('#retailAccountClose').onclick=()=>{resumeCheckout=false;dialog.close()};dialog.addEventListener('cancel',()=>{resumeCheckout=false});
 paintButton();
}
function paintButton(){const b=$('#retailAccountButton');if(!b)return;const s=session(),p=profile();b.textContent=s?(p.name||t('account')):t('login');b.classList.toggle('is-auth',!!s)}
function openAccount(mode='login'){ensureUi();const d=$('#retailAccountDialog');$('#retailAccountTitle').textContent=t('title');if(mode==='profile'&&session())renderProfile();else renderLogin();if(!d.open)d.showModal()}
function renderLogin(message=''){
 const p=profile();$('#retailAccountBody').innerHTML=`<p>${esc(t('intro'))}</p>${message?`<div class="retail-account-success">${esc(message)}</div>`:''}<label class="retail-account-field"><span>${esc(t('phone'))}</span><input id="retailOtpPhone" type="tel" inputmode="tel" autocomplete="tel" placeholder="${esc(t('phoneHint'))}" value="${esc(p.phone||'')}"></label><button class="retail-account-primary" id="retailOtpSend" type="button">${esc(t('send'))}</button><div class="retail-account-error" id="retailOtpError"></div><button class="retail-account-link" id="retailGuestContinue" type="button">${esc(t('guest'))}</button><p style="margin-top:6px;font-size:9px">${esc(t('guestHint'))}</p>`;
 $('#retailOtpSend').onclick=sendOtp;$('#retailGuestContinue').onclick=guestContinue;
}
async function authFetch(path,body){if(!cfg.url||!cfg.publishableKey)throw new Error('Supabase auth is not configured');const response=await fetch(`${cfg.url}/auth/v1/${path}`,{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!response.ok)throw new Error(data.msg||data.message||data.error_description||`Auth ${response.status}`);return data}
async function sendOtp(){const input=$('#retailOtpPhone'),error=$('#retailOtpError'),button=$('#retailOtpSend');requestedPhone=normalizePhone(input.value);if(!requestedPhone){error.textContent=t('badPhone');return}button.disabled=true;error.textContent='';try{await authFetch('otp',{phone:requestedPhone,create_user:true});renderVerify(t('sent'))}catch(e){console.warn('[Panora retail OTP]',e);error.textContent=e?.message||t('network')}finally{button.disabled=false}}
function renderVerify(message=''){ $('#retailAccountBody').innerHTML=`<div class="retail-account-success">${esc(message)}</div><label class="retail-account-field"><span>${esc(t('phone'))}</span><input value="${esc(requestedPhone)}" disabled></label><label class="retail-account-field"><span>${esc(t('code'))}</span><input id="retailOtpCode" inputmode="numeric" autocomplete="one-time-code" maxlength="8"></label><button class="retail-account-primary" id="retailOtpVerify" type="button">${esc(t('verify'))}</button><div class="retail-account-error" id="retailOtpError"></div>`;$('#retailOtpVerify').onclick=verifyOtp;$('#retailOtpCode').focus() }
async function verifyOtp(){const code=String($('#retailOtpCode').value||'').replace(/\s/g,''),error=$('#retailOtpError'),button=$('#retailOtpVerify');if(code.length<4){error.textContent=t('badCode');return}button.disabled=true;error.textContent='';try{const data=await authFetch('verify',{type:'sms',phone:requestedPhone,token:code});write(SESSION_KEY,{access_token:data.access_token||'',refresh_token:data.refresh_token||'',expires_at:Date.now()+Number(data.expires_in||3600)*1000,user:data.user||{phone:requestedPhone},phone:requestedPhone,verifiedAt:new Date().toISOString()});const p=profile();write(PROFILE_KEY,{...p,phone:requestedPhone});paintButton();$('#retailAccountDialog').close();if(resumeCheckout){resumeCheckout=false;setTimeout(()=>$('#retailCheckout')?.click(),0)}else openAccount('profile')}catch(e){console.warn('[Panora retail verify]',e);error.textContent=e?.message||t('network')}finally{button.disabled=false}}
function guestContinue(){try{sessionStorage.setItem(GUEST_KEY,'1')}catch{}$('#retailAccountDialog').close();if(resumeCheckout){resumeCheckout=false;setTimeout(()=>$('#retailCheckout')?.click(),0)}}
function renderProfile(){const s=session(),p=profile(),list=orders();if(!s){renderLogin();return}const phone=p.phone||s.phone||s.user?.phone||'';$('#retailAccountBody').innerHTML=`<div class="retail-account-profile"><div class="retail-account-profile-card"><strong>${esc(p.name||phone)}</strong><span>${esc(phone)} · ${esc(t('verified'))}</span></div><label class="retail-account-field"><span>${esc(t('name'))}</span><input id="retailProfileName" maxlength="120" autocomplete="name" value="${esc(p.name||'')}"></label><label class="retail-account-field"><span>${esc(t('email'))}</span><input id="retailProfileEmail" type="email" maxlength="160" autocomplete="email" value="${esc(p.email||'')}"></label><button class="retail-account-primary" id="retailProfileSave" type="button">${esc(t('save'))}</button><div class="retail-account-error" id="retailProfileMessage"></div><div style="margin-top:8px;font-weight:800;font-size:12px;color:#294534">${esc(t('orders'))}</div><div class="retail-account-orders">${list.length?list.map(o=>`<a class="retail-account-order" href="${esc(o.href)}"><strong>${esc(o.number||t('order'))}</strong><span>${esc(o.meta||'')}</span></a>`).join(''):`<div class="retail-account-empty">${esc(t('none'))}</div>`}</div><button class="retail-account-secondary" id="retailLogout" type="button">${esc(t('logout'))}</button></div>`;$('#retailProfileSave').onclick=()=>{write(PROFILE_KEY,{...p,phone,name:$('#retailProfileName').value.trim(),email:$('#retailProfileEmail').value.trim()});$('#retailProfileMessage').textContent=t('saved');paintButton()};$('#retailLogout').onclick=logout}
function logout(){try{localStorage.removeItem(SESSION_KEY)}catch{}paintButton();$('#retailAccountDialog').close()}
function guestAllowedOnce(){try{if(sessionStorage.getItem(GUEST_KEY)==='1'){sessionStorage.removeItem(GUEST_KEY);return true}}catch{}return false}
function guardCheckout(event){if(session()||guestAllowedOnce())return;event.preventDefault();event.stopImmediatePropagation();resumeCheckout=true;openAccount('login')}
function fillCheckout(){const form=$('#retailCustomerForm'),s=session(),p=profile();if(!form||!s)return;const phone=p.phone||s.phone||s.user?.phone||'';if(form.customerName&&!form.customerName.value)form.customerName.value=p.name||'';if(form.customerEmail&&!form.customerEmail.value)form.customerEmail.value=p.email||'';if(form.customerPhone){form.customerPhone.value=phone;form.customerPhone.readOnly=true;form.customerPhone.classList.add('retail-verified-phone');let note=$('#retailVerifiedPhoneNote');if(!note){note=document.createElement('div');note.id='retailVerifiedPhoneNote';note.className='retail-account-verified-note';form.customerPhone.closest('label')?.after(note)}note.textContent=`✓ ${t('verified')}: ${phone}`}}
function saveFormProfile(){const form=$('#retailCustomerForm'),s=session();if(!form||!s)return;const p=profile();write(PROFILE_KEY,{...p,phone:p.phone||s.phone||s.user?.phone||form.customerPhone?.value||'',name:form.customerName?.value?.trim()||p.name||'',email:form.customerEmail?.value?.trim()||p.email||''});paintButton()}
function captureSuccess(){const success=$('#retailSuccessView'),link=$('#retailSuccessOrderLink');if(!success||success.hidden||!link)return;const href=link.getAttribute('href')||'';if(!/retail-order\.html\?t=/.test(href))return;const number=$('#retailSuccessNumber')?.textContent?.trim()||'',meta=$('#retailSuccessMeta')?.textContent?.trim()||'';const list=orders().filter(o=>o.href!==href);list.unshift({href,number,meta,savedAt:new Date().toISOString()});write(ORDERS_KEY,list.slice(0,50));if(session())paintButton()}
function init(){ensureUi();const checkout=$('#retailCheckout');checkout?.addEventListener('click',guardCheckout,true);const dialog=$('#retailCheckoutDialog');if(dialog)new MutationObserver(()=>{if(dialog.open)fillCheckout();captureSuccess()}).observe(dialog,{attributes:true,subtree:true,attributeFilter:['open','hidden','href']});$('#retailCustomerForm')?.addEventListener('submit',saveFormProfile,true);document.addEventListener('visibilitychange',()=>{if(!document.hidden)paintButton()});window.addEventListener('storage',paintButton);paintButton()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.panoraRetailAccount={session,profile,orders,open:openAccount,logout};
})();
