-- Panora B2B · initial secure database schema
-- Run this entire file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

do $$ begin
  create type public.panora_role as enum ('admin', 'restaurant');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.order_status as enum ('submitted', 'confirmed', 'shipped', 'cancelled');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.payment_status as enum ('pending', 'confirmed', 'cancelled');
exception when duplicate_object then null;
end $$;

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  phone text,
  telegram text,
  address text,
  language text not null default 'ru' check (language in ('ru','en','es')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists restaurants_email_unique on public.restaurants (lower(email));

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.panora_role not null,
  restaurant_id uuid references public.restaurants(id) on delete set null,
  display_name text,
  created_at timestamptz not null default now(),
  constraint restaurant_profile_has_restaurant check (
    (role = 'admin' and restaurant_id is null) or
    (role = 'restaurant' and restaurant_id is not null)
  )
);

create table if not exists public.products (
  id text primary key,
  name_ru text not null,
  name_en text not null,
  name_es text not null,
  description_ru text not null default '',
  description_en text not null default '',
  description_es text not null default '',
  weight_g integer not null default 750 check (weight_g > 0),
  base_price numeric(10,2) not null default 0 check (base_price >= 0),
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurant_prices (
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  price numeric(10,2) not null check (price >= 0),
  updated_at timestamptz not null default now(),
  primary key (restaurant_id, product_id)
);

create table if not exists public.recipe_items (
  id uuid primary key default gen_random_uuid(),
  product_id text not null references public.products(id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  ingredient_name text not null,
  quantity numeric(12,3) not null default 0 check (quantity >= 0),
  unit text not null default 'g' check (unit in ('g','ml','pcs')),
  stock numeric(14,3) not null default 0 check (stock >= 0),
  margin numeric(7,2) not null default 5 check (margin >= 0),
  updated_at timestamptz not null default now(),
  unique (product_id, position)
);

create table if not exists public.bake_days (
  id uuid primary key default gen_random_uuid(),
  bake_date date not null unique,
  delivery_date date not null,
  cutoff_at timestamptz not null,
  accepting_orders boolean not null default true,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bake_items (
  bake_day_id uuid not null references public.bake_days(id) on delete cascade,
  product_id text not null references public.products(id) on delete cascade,
  planned_quantity integer not null default 0 check (planned_quantity >= 0),
  primary key (bake_day_id, product_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  restaurant_id uuid not null references public.restaurants(id),
  bake_day_id uuid not null references public.bake_days(id),
  status public.order_status not null default 'submitted',
  comment text,
  cancelled_reason text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0),
  unique (order_id, product_id)
);

create table if not exists public.delivery_notes (
  id uuid primary key default gen_random_uuid(),
  note_number bigint generated by default as identity unique,
  order_id uuid not null unique references public.orders(id),
  restaurant_id uuid not null references public.restaurants(id),
  delivered_at timestamptz not null default now(),
  total numeric(12,2) not null check (total >= 0),
  qr_token uuid not null default gen_random_uuid() unique,
  customer_confirmed_at timestamptz,
  customer_receiver text,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id),
  delivery_note_id uuid references public.delivery_notes(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  method text not null,
  note text,
  status public.payment_status not null default 'pending',
  received_at timestamptz not null default now(),
  confirmed_at timestamptz,
  confirmed_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create or replace function public.panora_is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin') $$;

create or replace function public.panora_restaurant_id()
returns uuid language sql stable security definer set search_path = public
as $$ select p.restaurant_id from public.profiles p where p.id = auth.uid() $$;

alter table public.restaurants enable row level security;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.restaurant_prices enable row level security;
alter table public.recipe_items enable row level security;
alter table public.bake_days enable row level security;
alter table public.bake_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_notes enable row level security;
alter table public.payments enable row level security;

drop policy if exists profiles_read_self_or_admin on public.profiles;
create policy profiles_read_self_or_admin on public.profiles for select to authenticated
using (id = auth.uid() or public.panora_is_admin());

drop policy if exists admin_all_restaurants on public.restaurants;
create policy admin_all_restaurants on public.restaurants for all to authenticated
using (public.panora_is_admin()) with check (public.panora_is_admin());
drop policy if exists restaurant_read_self on public.restaurants;
create policy restaurant_read_self on public.restaurants for select to authenticated
using (id = public.panora_restaurant_id());

drop policy if exists products_read_authenticated on public.products;
create policy products_read_authenticated on public.products for select to authenticated using (active or public.panora_is_admin());
drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());

drop policy if exists recipe_items_admin_read on public.recipe_items;
create policy recipe_items_admin_read on public.recipe_items for select to authenticated using (public.panora_is_admin());
drop policy if exists recipe_items_admin_write on public.recipe_items;
create policy recipe_items_admin_write on public.recipe_items for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());

drop policy if exists prices_admin_all on public.restaurant_prices;
create policy prices_admin_all on public.restaurant_prices for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());
drop policy if exists prices_restaurant_read_own on public.restaurant_prices;
create policy prices_restaurant_read_own on public.restaurant_prices for select to authenticated using (restaurant_id = public.panora_restaurant_id());

drop policy if exists bake_days_read_authenticated on public.bake_days;
create policy bake_days_read_authenticated on public.bake_days for select to authenticated using (true);
drop policy if exists bake_days_admin_write on public.bake_days;
create policy bake_days_admin_write on public.bake_days for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());

drop policy if exists bake_items_read_authenticated on public.bake_items;
create policy bake_items_read_authenticated on public.bake_items for select to authenticated using (true);
drop policy if exists bake_items_admin_write on public.bake_items;
create policy bake_items_admin_write on public.bake_items for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());

drop policy if exists orders_admin_all on public.orders;
create policy orders_admin_all on public.orders for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());
drop policy if exists orders_restaurant_read on public.orders;
create policy orders_restaurant_read on public.orders for select to authenticated using (restaurant_id = public.panora_restaurant_id());
drop policy if exists orders_restaurant_insert on public.orders;
create policy orders_restaurant_insert on public.orders for insert to authenticated with check (restaurant_id = public.panora_restaurant_id() and created_by = auth.uid());
drop policy if exists orders_restaurant_cancel on public.orders;
create policy orders_restaurant_cancel on public.orders for update to authenticated using (restaurant_id = public.panora_restaurant_id() and status = 'submitted') with check (restaurant_id = public.panora_restaurant_id() and status = 'cancelled');

drop policy if exists order_items_admin_all on public.order_items;
create policy order_items_admin_all on public.order_items for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());
drop policy if exists order_items_restaurant_read on public.order_items;
create policy order_items_restaurant_read on public.order_items for select to authenticated using (exists(select 1 from public.orders o where o.id = order_id and o.restaurant_id = public.panora_restaurant_id()));
drop policy if exists order_items_restaurant_insert on public.order_items;
create policy order_items_restaurant_insert on public.order_items for insert to authenticated with check (exists(select 1 from public.orders o where o.id = order_id and o.restaurant_id = public.panora_restaurant_id() and o.status = 'submitted'));

drop policy if exists delivery_notes_admin_all on public.delivery_notes;
create policy delivery_notes_admin_all on public.delivery_notes for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());
drop policy if exists delivery_notes_restaurant_read on public.delivery_notes;
create policy delivery_notes_restaurant_read on public.delivery_notes for select to authenticated using (restaurant_id = public.panora_restaurant_id());

drop policy if exists payments_admin_all on public.payments;
create policy payments_admin_all on public.payments for all to authenticated using (public.panora_is_admin()) with check (public.panora_is_admin());
drop policy if exists payments_restaurant_read on public.payments;
create policy payments_restaurant_read on public.payments for select to authenticated using (restaurant_id = public.panora_restaurant_id());

insert into public.products (id,name_ru,name_en,name_es,description_ru,description_en,description_es,weight_g,base_price)
values
 ('plain','Льняной бездрожжевой хлеб с семенами','Yeast-free flaxseed bread with seeds','Pan de lino sin levadura con semillas','Бездрожжевой хлеб с семенами льна.','Yeast-free bread with flax seeds.','Pan sin levadura con semillas de lino.',750,4.50),
 ('pumpkin','Тыквенный бездрожжевой хлеб с семенами','Yeast-free pumpkin bread with seeds','Pan de calabaza sin levadura con semillas','Бездрожжевой тыквенный хлеб с семенами.','Yeast-free pumpkin bread with seeds.','Pan de calabaza sin levadura con semillas.',750,5.00)
on conflict (id) do update set
 name_ru=excluded.name_ru,name_en=excluded.name_en,name_es=excluded.name_es,
 description_ru=excluded.description_ru,description_en=excluded.description_en,description_es=excluded.description_es,
 weight_g=excluded.weight_g,base_price=excluded.base_price;

-- Panora v221: secure, restaurant-bound delivery QR confirmation.
-- Run this file once in Supabase SQL Editor.

create or replace function public.panora_delivery_confirmation(p_token uuid)
returns table (
  note_id uuid,
  note_number bigint,
  order_id uuid,
  order_number bigint,
  delivered_at timestamptz,
  delivery_date date,
  customer_confirmed_at timestamptz,
  customer_receiver text,
  items jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  select
    dn.id,
    dn.note_number,
    dn.order_id,
    o.order_number,
    dn.delivered_at,
    bd.delivery_date,
    dn.customer_confirmed_at,
    dn.customer_receiver,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'product_id', oi.product_id,
          'name_ru', p.name_ru,
          'name_en', p.name_en,
          'name_es', p.name_es,
          'quantity', oi.quantity
        )
        order by oi.product_id
      ) filter (where oi.product_id is not null),
      '[]'::jsonb
    )
  from public.delivery_notes dn
  join public.orders o on o.id = dn.order_id
  join public.profiles profile
    on profile.id = auth.uid()
   and profile.role = 'restaurant'
   and profile.restaurant_id = dn.restaurant_id
  left join public.bake_days bd on bd.id = o.bake_day_id
  left join public.order_items oi on oi.order_id = o.id
  left join public.products p on p.id = oi.product_id
  where dn.qr_token = p_token
    and (
      dn.customer_confirmed_at is not null
      or dn.delivered_at >= now() - interval '48 hours'
    )
  group by dn.id, dn.note_number, dn.order_id, o.order_number,
           dn.delivered_at, bd.delivery_date,
           dn.customer_confirmed_at, dn.customer_receiver;
$$;

create or replace function public.panora_confirm_delivery(
  p_token uuid,
  p_receiver text
)
returns table (
  note_id uuid,
  customer_confirmed_at timestamptz,
  customer_receiver text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  restaurant uuid;
begin
  select profile.restaurant_id
    into restaurant
  from public.profiles profile
  where profile.id = auth.uid()
    and profile.role = 'restaurant';

  if restaurant is null then
    return;
  end if;

  if length(trim(coalesce(p_receiver, ''))) < 2
     or length(trim(p_receiver)) > 120 then
    raise exception 'Invalid receiver';
  end if;

  return query
  update public.delivery_notes dn
     set customer_confirmed_at = coalesce(dn.customer_confirmed_at, now()),
         customer_receiver = case
           when dn.customer_confirmed_at is null then trim(p_receiver)
           else dn.customer_receiver
         end
   where dn.qr_token = p_token
     and dn.restaurant_id = restaurant
     and (
       dn.customer_confirmed_at is not null
       or dn.delivered_at >= now() - interval '48 hours'
     )
  returning dn.id, dn.customer_confirmed_at, dn.customer_receiver;
end;
$$;

revoke all on function public.panora_delivery_confirmation(uuid) from public, anon;
revoke all on function public.panora_confirm_delivery(uuid, text) from public, anon;
grant execute on function public.panora_delivery_confirmation(uuid) to authenticated;
grant execute on function public.panora_confirm_delivery(uuid, text) to authenticated;
