const fs=require('fs');
const assert=require('assert');
const read=name=>fs.readFileSync(name,'utf8');
const product=read('product-admin.js');
const calendar=read('calendar-plan.js');
const admin=read('admin.js');
const commerce=read('commerce.js');
const app=read('app.js');
const purchase=read('purchase-costs.js');
const html=read('admin.html');
const build=JSON.parse(read('build.json'));

assert.equal(build.version,'11.13');
assert.equal(build.build,11130);
assert.equal(build.cache,11130);
assert.match(product,/data-plan-enabled/);
assert.match(product,/Quantity is optional|Количество необязательно/);
assert.match(product,/planned=String\(input\?\.value\|\|''\)\.trim\(\)===''\?0/);
assert.match(product,/Select at least one bread|Отметьте хотя бы один хлеб/);
assert.doesNotMatch(product,/Укажите количество хотя бы одного хлеба/);
assert.match(calendar,/план без количества/);
assert.match(calendar,/window\.panoraBuildPlanProductFields\?\.\(date\)/);
assert.match(commerce,/planned: 0,\s*ordered: g\.ordered/);
assert.match(app,/function catalogAvailablePieces\(id\).*eligible\.length\?MAX_PIECES_PER_PRODUCT:0/s);
assert.doesNotMatch(app,/planPlannedPieces\(p\)>0/);
assert.match(admin,/suggested=Math\.max\(0,orderQty,Number\(plan\.planOrdered\|\|0\),Number\(plan\.planned\|\|0\)\)/);
assert.match(purchase,/manual>current\)products\.set\(product,manual\)/);
assert.match(html,/Отметьте хлеб, который планируется выпекать/);
assert.match(admin,/panora:b2b-shipment/);
assert.match(admin,/replace\(\/\\s\*·\?\\s\*\\\[panora:b2b-shipment/);
console.log('Panora 10.75 bake-day selection tests: OK');
