const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const build=JSON.parse(fs.readFileSync('build.json','utf8'));assert.deepEqual(build,{version:'10.91',build:10910,cache:10910});
const admin=fs.readFileSync('admin.html','utf8'),bakery=fs.readFileSync('bakery/index.html','utf8'),js=fs.readFileSync('production-safety.js','utf8'),css=fs.readFileSync('production-safety.css','utf8');
const views=['ps-haccp','ps-capa','ps-recalls','ps-suppliers','ps-training'];for(const html of [admin,bakery])for(const view of views){assert(html.includes(`data-view="${view}"`),`menu missing ${view}`);assert(html.includes(`id="view-${view}"`),`view missing ${view}`)}
for(const token of ['haccpPlans:[]','capaCases:[]','recalls:[]','approvedSuppliers:[]','trainingRecords:[]','function renderHaccp','function renderCapa','function renderRecalls','function renderSuppliers','function renderTraining','function recallRecipients','function recallNoticeText','data-ps-recall-sent','data-ps-recall-ack','psApprovedSupplierOptions'])assert(js.includes(token),`missing ${token}`);
assert(js.includes("lot.blocked=true"),'actual recall must block LOT');assert(js.includes("supplierRec?.status==='blocked'"),'blocked supplier guard missing');assert(css.includes('.ps-recall-recipients'));assert(css.includes('.ps-overdue'));
// Runtime merge + recall recipient aggregation test without initializing the UI.
let source=js.replace("if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();\n})();",`window.__docsTest={normalizeState,mergeState,recallRecipients};\nif(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();\n})();`);
class Storage{constructor(){this.m=new Map()}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}removeItem(k){this.m.delete(k)}}
const storage=new Storage();storage.setItem('panora-admin-lang','ru');storage.setItem('panora-restaurants',JSON.stringify([{id:'r1',name:'Cafe Uno'},{id:'r2',name:'Hotel Dos'}]));storage.setItem('panora-production-safety-v1066',JSON.stringify({breadLots:[{id:'lot1',number:'LOT-X',product:'p1',date:'2026-09-16',quantity:10,updatedAt:'2026-09-16T10:00:00Z'}],allocations:[{id:'a1',lotId:'lot1',sourceType:'b2b',restaurantId:'r1',quantity:3,label:'DN-1',updatedAt:'2026-09-16T10:00:00Z'},{id:'a2',lotId:'lot1',sourceType:'b2b',restaurantId:'r1',quantity:2,label:'DN-2',updatedAt:'2026-09-16T10:01:00Z'},{id:'a3',lotId:'lot1',sourceType:'b2b',restaurantId:'r2',quantity:1,label:'DN-3',updatedAt:'2026-09-16T10:02:00Z'}],approvedSuppliers:[{id:'s1',name:'Flour SL',status:'approved',updatedAt:'2026-09-16T10:00:00Z'}],haccpPlans:[],capaCases:[],recalls:[],trainingRecords:[]}));
const document={readyState:'loading',body:{classList:{contains:()=>true}},addEventListener:()=>{},querySelector(sel){if(sel==='#adminLanguage')return {value:'ru'};return null},querySelectorAll:()=>[]};
const window={PANORA_SUPABASE:{},panoraSupabaseSession:null,addEventListener:()=>{},dispatchEvent:()=>{},panoraProductRegistry:()=>[{id:'p1',names:{ru:'Хлеб'}}]};
const ctx={window,document,localStorage:storage,navigator:{onLine:false},crypto:{randomUUID:()=>crypto.randomUUID()},structuredClone,CustomEvent:function(){},Intl,Date,Math,JSON,Number,String,Array,Object,Set,Map,Promise,console,setTimeout:()=>0,clearTimeout:()=>{},fetch:async()=>{},Notification:{permission:'denied'},FormData:function(){},confirm:()=>true,prompt:()=>null,alert:()=>{}};Object.assign(window,{window,document,localStorage:storage,navigator:ctx.navigator,crypto:ctx.crypto,CustomEvent:ctx.CustomEvent,Notification:ctx.Notification});vm.createContext(ctx);vm.runInContext(source,ctx,{filename:'production-safety.js'});
const api=window.__docsTest;const normalized=api.normalizeState({});for(const k of ['haccpPlans','capaCases','recalls','approvedSuppliers','trainingRecords'])assert(Array.isArray(normalized[k]),`${k} not normalized`);
const merged=api.mergeState({approvedSuppliers:[{id:'s1',name:'old',updatedAt:'2026-09-16T09:00:00Z'}]},{approvedSuppliers:[{id:'s1',name:'new',updatedAt:'2026-09-16T11:00:00Z'}]});assert.equal(merged.approvedSuppliers[0].name,'new');
const rec=api.recallRecipients({lotId:'lot1'});assert.equal(rec.length,2);const cafe=rec.find(x=>x.restaurantId==='r1');assert.equal(cafe.quantity,5);assert.deepEqual([...cafe.labels],['DN-1','DN-2']);
console.log('Panora 10.75 compliance documentation tests: OK');
