const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const app=path.join(__dirname,'../app');
const sync=fs.readFileSync(path.join(app,'admin-status-sync.js'),'utf8');
const cloud=fs.readFileSync(path.join(app,'cloud-sync.js'),'utf8');
const note=fs.readFileSync(path.join(app,'event-notifications.js'),'utf8');
assert.doesNotMatch(sync,/План обновлён с другого устройства/);
assert.match(cloud,/source:'cloud-remote'/);
assert.match(note,/calendarVisible/);
assert.match(note,/state\.textContent='План обновлён'/);
assert.doesNotMatch(note,/Получены изменения с другого устройства/);
console.log('v335.6-remote-plan-status: 5 assertions passed');
