const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const app=path.join(__dirname,'../app');
const appjs=fs.readFileSync(path.join(app,'app.js'),'utf8');
const rw=fs.readFileSync(path.join(app,'restaurant-workspace.js'),'utf8');
const note=fs.readFileSync(path.join(app,'event-notifications.js'),'utf8');
assert.match(appjs,/panoraOpenPartnerOrders/);
assert.match(rw,/orderView = "active"/);
assert.match(rw,/data-rw-order-view="history"/);
assert.doesNotMatch(note,/modern-bell/);
console.log('v336.7-orders-no-floating-bell: 4 assertions passed');
