const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const app=path.join(__dirname,'../app');
const audit=fs.readFileSync(path.join(app,'audit-trail.js'),'utf8');
const note=fs.readFileSync(path.join(app,'event-notifications.js'),'utf8');
const auditCss=fs.readFileSync(path.join(app,'audit-trail.css'),'utf8');
const noteCss=fs.readFileSync(path.join(app,'event-notifications.css'),'utf8');
assert.match(audit,/utilityZone\(\)\.appendChild\(b\)/);
assert.match(note,/utilityZone\(\)\.appendChild\(b\)/);
assert.match(audit,/↺/);
assert.match(note,/Звук/);
assert.match(noteCss,/\.panora-utility-zone\{/);
assert.match(noteCss,/top:64px;right:12px/);
assert.match(noteCss,/\.panora-utility-zone \.panora-event-settings/);
assert.match(auditCss,/\.panora-utility-zone \.panora-audit-button/);
assert.match(noteCss,/@media\(max-width:720px\)/);
console.log('v336.4-utility-zone: 9 assertions passed');
